// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: mapsvr/bigmapmarch.proto

package mapsvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TroopType 兵种类型
type TroopType int32

const (
	TroopType_TROOP_TYPE_UNSPECIFIED TroopType = 0
	TroopType_INFANTRY               TroopType = 1 // 步兵
	TroopType_CAVALRY                TroopType = 2 // 骑兵
	TroopType_ARCHER                 TroopType = 3 // 弓兵
)

// Enum value maps for TroopType.
var (
	TroopType_name = map[int32]string{
		0: "TROOP_TYPE_UNSPECIFIED",
		1: "INFANTRY",
		2: "CAVALRY",
		3: "ARCHER",
	}
	TroopType_value = map[string]int32{
		"TROOP_TYPE_UNSPECIFIED": 0,
		"INFANTRY":               1,
		"CAVALRY":                2,
		"ARCHER":                 3,
	}
)

func (x TroopType) Enum() *TroopType {
	p := new(TroopType)
	*p = x
	return p
}

func (x TroopType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TroopType) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[0].Descriptor()
}

func (TroopType) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[0]
}

func (x TroopType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TroopType.Descriptor instead.
func (TroopType) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{0}
}

// MarchType 行军类型，决定行军到达后的行为
type MarchType int32

const (
	MarchType_MARCH_TYPE_UNSPECIFIED MarchType = 0
	MarchType_MARCH_TYPE_ATTACK      MarchType = 1 // 出征攻击：到达后触发战斗
	MarchType_MARCH_TYPE_GATHER      MarchType = 2 // 采集资源：到达后进入采集状态
	MarchType_MARCH_TYPE_SCOUT       MarchType = 3 // 侦察：到达后获取目标信息并返回
	MarchType_MARCH_TYPE_RALLY       MarchType = 4 // 集结（参与者）：加入他人发起的集结
	MarchType_MARCH_TYPE_REINFORCE   MarchType = 5 // 援军驻防：到达后驻守在目标位置
	MarchType_MARCH_TYPE_RETURN      MarchType = 6 // 回城：部队返回出发地
	MarchType_MARCH_TYPE_RALLY_LEAD  MarchType = 7 // 集结发起者：发起集结的那路部队
)

// Enum value maps for MarchType.
var (
	MarchType_name = map[int32]string{
		0: "MARCH_TYPE_UNSPECIFIED",
		1: "MARCH_TYPE_ATTACK",
		2: "MARCH_TYPE_GATHER",
		3: "MARCH_TYPE_SCOUT",
		4: "MARCH_TYPE_RALLY",
		5: "MARCH_TYPE_REINFORCE",
		6: "MARCH_TYPE_RETURN",
		7: "MARCH_TYPE_RALLY_LEAD",
	}
	MarchType_value = map[string]int32{
		"MARCH_TYPE_UNSPECIFIED": 0,
		"MARCH_TYPE_ATTACK":      1,
		"MARCH_TYPE_GATHER":      2,
		"MARCH_TYPE_SCOUT":       3,
		"MARCH_TYPE_RALLY":       4,
		"MARCH_TYPE_REINFORCE":   5,
		"MARCH_TYPE_RETURN":      6,
		"MARCH_TYPE_RALLY_LEAD":  7,
	}
)

func (x MarchType) Enum() *MarchType {
	p := new(MarchType)
	*p = x
	return p
}

func (x MarchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarchType) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[1].Descriptor()
}

func (MarchType) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[1]
}

func (x MarchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarchType.Descriptor instead.
func (MarchType) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{1}
}

// MarchState 行军状态，表示行军当前所处的阶段
type MarchState int32

const (
	MarchState_MARCH_STATE_UNSPECIFIED MarchState = 0
	MarchState_MARCH_STATE_MARCHING    MarchState = 1 // 行进中：部队正在从出发地移动到目标地
	MarchState_MARCH_STATE_FIGHTING    MarchState = 2 // 战斗中：部队已到达目标，正在战斗
	MarchState_MARCH_STATE_GATHERING   MarchState = 3 // 采集中：部队正在资源点采集资源
	MarchState_MARCH_STATE_STATIONED   MarchState = 4 // 驻防中：援军部队驻守在目标位置
	MarchState_MARCH_STATE_SCOUTING    MarchState = 5 // 侦察中：部队正在侦察目标
	MarchState_MARCH_STATE_RETURNING   MarchState = 6 // 返回中：部队正在返回出发地
)

// Enum value maps for MarchState.
var (
	MarchState_name = map[int32]string{
		0: "MARCH_STATE_UNSPECIFIED",
		1: "MARCH_STATE_MARCHING",
		2: "MARCH_STATE_FIGHTING",
		3: "MARCH_STATE_GATHERING",
		4: "MARCH_STATE_STATIONED",
		5: "MARCH_STATE_SCOUTING",
		6: "MARCH_STATE_RETURNING",
	}
	MarchState_value = map[string]int32{
		"MARCH_STATE_UNSPECIFIED": 0,
		"MARCH_STATE_MARCHING":    1,
		"MARCH_STATE_FIGHTING":    2,
		"MARCH_STATE_GATHERING":   3,
		"MARCH_STATE_STATIONED":   4,
		"MARCH_STATE_SCOUTING":    5,
		"MARCH_STATE_RETURNING":   6,
	}
)

func (x MarchState) Enum() *MarchState {
	p := new(MarchState)
	*p = x
	return p
}

func (x MarchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarchState) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[2].Descriptor()
}

func (MarchState) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[2]
}

func (x MarchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarchState.Descriptor instead.
func (MarchState) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{2}
}

// TargetType 行军目标类型
type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED TargetType = 0
	TargetType_TARGET_TYPE_PLAYER_CITY TargetType = 1 // 玩家城池
	TargetType_TARGET_TYPE_MONSTER     TargetType = 2 // 野怪
	TargetType_TARGET_TYPE_RESOURCE    TargetType = 3 // 资源点
	TargetType_TARGET_TYPE_ALLIANCE    TargetType = 4 // 联盟建筑
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "TARGET_TYPE_PLAYER_CITY",
		2: "TARGET_TYPE_MONSTER",
		3: "TARGET_TYPE_RESOURCE",
		4: "TARGET_TYPE_ALLIANCE",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"TARGET_TYPE_PLAYER_CITY": 1,
		"TARGET_TYPE_MONSTER":     2,
		"TARGET_TYPE_RESOURCE":    3,
		"TARGET_TYPE_ALLIANCE":    4,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[3].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[3]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{3}
}

// RallyState 集结状态
type RallyState int32

const (
	RallyState_RALLY_STATE_UNSPECIFIED RallyState = 0
	RallyState_RALLY_STATE_WAITING     RallyState = 1 // 等待成员加入
	RallyState_RALLY_STATE_MARCHING    RallyState = 2 // 集结部队行军中
	RallyState_RALLY_STATE_FIGHTING    RallyState = 3 // 集结部队战斗中
	RallyState_RALLY_STATE_ENDED       RallyState = 4 // 集结已结束
)

// Enum value maps for RallyState.
var (
	RallyState_name = map[int32]string{
		0: "RALLY_STATE_UNSPECIFIED",
		1: "RALLY_STATE_WAITING",
		2: "RALLY_STATE_MARCHING",
		3: "RALLY_STATE_FIGHTING",
		4: "RALLY_STATE_ENDED",
	}
	RallyState_value = map[string]int32{
		"RALLY_STATE_UNSPECIFIED": 0,
		"RALLY_STATE_WAITING":     1,
		"RALLY_STATE_MARCHING":    2,
		"RALLY_STATE_FIGHTING":    3,
		"RALLY_STATE_ENDED":       4,
	}
)

func (x RallyState) Enum() *RallyState {
	p := new(RallyState)
	*p = x
	return p
}

func (x RallyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RallyState) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[4].Descriptor()
}

func (RallyState) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[4]
}

func (x RallyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RallyState.Descriptor instead.
func (RallyState) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{4}
}

// TroopLevels 某一兵种各等级的数量分布，key=兵等级, value=数量
type TroopLevels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LevelCounts   map[int32]int32        `protobuf:"bytes,1,rep,name=level_counts,json=levelCounts,proto3" json:"level_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TroopLevels) Reset() {
	*x = TroopLevels{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TroopLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TroopLevels) ProtoMessage() {}

func (x *TroopLevels) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TroopLevels.ProtoReflect.Descriptor instead.
func (*TroopLevels) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{0}
}

func (x *TroopLevels) GetLevelCounts() map[int32]int32 {
	if x != nil {
		return x.LevelCounts
	}
	return nil
}

// MarchInfo 行军完整信息
// 客户端维护 map[march_id]*MarchInfo 的本地缓存表
// 服务端通过 MarchCreateNotify/MarchStateNotify 推送此结构，客户端直接覆盖缓存即可
type MarchInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`                                                           // 行军唯一 ID
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`                                                         // 发起行军的玩家 ID
	MarchType     MarchType              `protobuf:"varint,3,opt,name=march_type,json=marchType,proto3,enum=mapsvr.MarchType" json:"march_type,omitempty"`                               // 行军类型
	State         MarchState             `protobuf:"varint,4,opt,name=state,proto3,enum=mapsvr.MarchState" json:"state,omitempty"`                                                       // 当前状态
	FromPos       *Position              `protobuf:"bytes,5,opt,name=from_pos,json=fromPos,proto3" json:"from_pos,omitempty"`                                                            // 出发坐标
	ToPos         *Position              `protobuf:"bytes,6,opt,name=to_pos,json=toPos,proto3" json:"to_pos,omitempty"`                                                                  // 目标坐标
	StartAt       int64                  `protobuf:"varint,7,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`                                                           // 出发时间戳（秒）
	ArriveAt      int64                  `protobuf:"varint,8,opt,name=arrive_at,json=arriveAt,proto3" json:"arrive_at,omitempty"`                                                        // 预计到达时间戳（秒），客户端据此做线性插值
	TargetType    TargetType             `protobuf:"varint,9,opt,name=target_type,json=targetType,proto3,enum=mapsvr.TargetType" json:"target_type,omitempty"`                           // 目标类型
	TargetId      int64                  `protobuf:"varint,10,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                                                       // 目标实体 ID
	HeroIds       []int64                `protobuf:"varint,11,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`                                                   // 出征英雄 ID 列表
	Troops        map[int32]*TroopLevels `protobuf:"bytes,12,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 兵种->等级数量，key 为 TroopType 的 int32 值
	RallyId       int64                  `protobuf:"varint,13,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`                                                          // 所属集结 ID，0 表示非集结行军
	ExpeditionId  int64                  `protobuf:"varint,14,opt,name=expedition_id,json=expeditionId,proto3" json:"expedition_id,omitempty"`                                           // 行军流程标识，去程与回程共享同一值（等于首条出征行军的 MarchID）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarchInfo) Reset() {
	*x = MarchInfo{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchInfo) ProtoMessage() {}

func (x *MarchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchInfo.ProtoReflect.Descriptor instead.
func (*MarchInfo) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{1}
}

func (x *MarchInfo) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *MarchInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MarchInfo) GetMarchType() MarchType {
	if x != nil {
		return x.MarchType
	}
	return MarchType_MARCH_TYPE_UNSPECIFIED
}

func (x *MarchInfo) GetState() MarchState {
	if x != nil {
		return x.State
	}
	return MarchState_MARCH_STATE_UNSPECIFIED
}

func (x *MarchInfo) GetFromPos() *Position {
	if x != nil {
		return x.FromPos
	}
	return nil
}

func (x *MarchInfo) GetToPos() *Position {
	if x != nil {
		return x.ToPos
	}
	return nil
}

func (x *MarchInfo) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *MarchInfo) GetArriveAt() int64 {
	if x != nil {
		return x.ArriveAt
	}
	return 0
}

func (x *MarchInfo) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *MarchInfo) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *MarchInfo) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

func (x *MarchInfo) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

func (x *MarchInfo) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

func (x *MarchInfo) GetExpeditionId() int64 {
	if x != nil {
		return x.ExpeditionId
	}
	return 0
}

// RallyMemberInfo 集结中某一成员的参与信息
type RallyMemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`                                                        // 成员玩家 ID
	Troops        map[int32]*TroopLevels `protobuf:"bytes,2,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 该成员派出的兵种
	HeroIds       []int64                `protobuf:"varint,3,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`                                                   // 该成员派出的英雄
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RallyMemberInfo) Reset() {
	*x = RallyMemberInfo{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RallyMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RallyMemberInfo) ProtoMessage() {}

func (x *RallyMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RallyMemberInfo.ProtoReflect.Descriptor instead.
func (*RallyMemberInfo) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{2}
}

func (x *RallyMemberInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RallyMemberInfo) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

func (x *RallyMemberInfo) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

// RallyInfo 集结完整信息，用于联盟内广播和玩家进入地图同步
type RallyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RallyId       int64                  `protobuf:"varint,1,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`                                 // 集结唯一 ID
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`                               // 发起者玩家 ID
	AllianceId    string                 `protobuf:"bytes,3,opt,name=alliance_id,json=allianceId,proto3" json:"alliance_id,omitempty"`                         // 所属联盟 ID
	TargetPos     *Position              `protobuf:"bytes,4,opt,name=target_pos,json=targetPos,proto3" json:"target_pos,omitempty"`                            // 目标坐标
	TargetType    TargetType             `protobuf:"varint,5,opt,name=target_type,json=targetType,proto3,enum=mapsvr.TargetType" json:"target_type,omitempty"` // 目标类型
	TargetId      int64                  `protobuf:"varint,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                              // 目标实体 ID
	MaxCapacity   int64                  `protobuf:"varint,7,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`                     // 集结最大兵力容量
	CreateAt      int64                  `protobuf:"varint,8,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`                              // 创建时间戳（秒）
	LaunchAt      int64                  `protobuf:"varint,9,opt,name=launch_at,json=launchAt,proto3" json:"launch_at,omitempty"`                              // 预计发起时间戳（秒）= create_at + wait_duration
	State         RallyState             `protobuf:"varint,10,opt,name=state,proto3,enum=mapsvr.RallyState" json:"state,omitempty"`                            // 当前集结状态
	Members       []*RallyMemberInfo     `protobuf:"bytes,11,rep,name=members,proto3" json:"members,omitempty"`                                                // 已加入的成员列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RallyInfo) Reset() {
	*x = RallyInfo{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RallyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RallyInfo) ProtoMessage() {}

func (x *RallyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RallyInfo.ProtoReflect.Descriptor instead.
func (*RallyInfo) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{3}
}

func (x *RallyInfo) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

func (x *RallyInfo) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *RallyInfo) GetAllianceId() string {
	if x != nil {
		return x.AllianceId
	}
	return ""
}

func (x *RallyInfo) GetTargetPos() *Position {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

func (x *RallyInfo) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *RallyInfo) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *RallyInfo) GetMaxCapacity() int64 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *RallyInfo) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *RallyInfo) GetLaunchAt() int64 {
	if x != nil {
		return x.LaunchAt
	}
	return 0
}

func (x *RallyInfo) GetState() RallyState {
	if x != nil {
		return x.State
	}
	return RallyState_RALLY_STATE_UNSPECIFIED
}

func (x *RallyInfo) GetMembers() []*RallyMemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

// StartMarchRequest 创建行军请求
// 路由: mapsvr.bigmapmarch.startmarch
// 出发坐标由服务端从玩家城池位置读取，客户端无需传入
type StartMarchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchType     MarchType              `protobuf:"varint,1,opt,name=march_type,json=marchType,proto3,enum=mapsvr.MarchType" json:"march_type,omitempty"`                              // 行军类型
	ToPos         *Position              `protobuf:"bytes,2,opt,name=to_pos,json=toPos,proto3" json:"to_pos,omitempty"`                                                                 // 目标坐标
	TargetType    TargetType             `protobuf:"varint,3,opt,name=target_type,json=targetType,proto3,enum=mapsvr.TargetType" json:"target_type,omitempty"`                          // 目标类型
	TargetId      int64                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                                                       // 目标实体 ID
	HeroIds       []int64                `protobuf:"varint,5,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`                                                   // 派出的英雄 ID 列表
	Troops        map[int32]*TroopLevels `protobuf:"bytes,6,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 派出的兵种
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMarchRequest) Reset() {
	*x = StartMarchRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMarchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMarchRequest) ProtoMessage() {}

func (x *StartMarchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMarchRequest.ProtoReflect.Descriptor instead.
func (*StartMarchRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{4}
}

func (x *StartMarchRequest) GetMarchType() MarchType {
	if x != nil {
		return x.MarchType
	}
	return MarchType_MARCH_TYPE_UNSPECIFIED
}

func (x *StartMarchRequest) GetToPos() *Position {
	if x != nil {
		return x.ToPos
	}
	return nil
}

func (x *StartMarchRequest) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *StartMarchRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *StartMarchRequest) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

func (x *StartMarchRequest) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

// StartMarchResponse 创建行军响应，成功时返回完整行军信息
type StartMarchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	March         *MarchInfo             `protobuf:"bytes,2,opt,name=march,proto3" json:"march,omitempty"` // 创建成功后的完整行军信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMarchResponse) Reset() {
	*x = StartMarchResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMarchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMarchResponse) ProtoMessage() {}

func (x *StartMarchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMarchResponse.ProtoReflect.Descriptor instead.
func (*StartMarchResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{5}
}

func (x *StartMarchResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *StartMarchResponse) GetMarch() *MarchInfo {
	if x != nil {
		return x.March
	}
	return nil
}

// CancelMarchRequest 取消/召回行军请求
// 路由: mapsvr.bigmapmarch.cancelmarch
// 行军将反转方向，以已行进时间等比计算返回时间
type CancelMarchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMarchRequest) Reset() {
	*x = CancelMarchRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMarchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMarchRequest) ProtoMessage() {}

func (x *CancelMarchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMarchRequest.ProtoReflect.Descriptor instead.
func (*CancelMarchRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{6}
}

func (x *CancelMarchRequest) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

// CancelMarchResponse 取消行军响应
type CancelMarchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMarchResponse) Reset() {
	*x = CancelMarchResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMarchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMarchResponse) ProtoMessage() {}

func (x *CancelMarchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMarchResponse.ProtoReflect.Descriptor instead.
func (*CancelMarchResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{7}
}

func (x *CancelMarchResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

// SpeedUpMarchRequest 使用加速道具加速行军
// 路由: mapsvr.bigmapmarch.speedupmarch
type SpeedUpMarchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"` // 要加速的行军 ID
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`    // 加速道具 ID
	ItemNum       int32                  `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"` // 使用数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedUpMarchRequest) Reset() {
	*x = SpeedUpMarchRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedUpMarchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedUpMarchRequest) ProtoMessage() {}

func (x *SpeedUpMarchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedUpMarchRequest.ProtoReflect.Descriptor instead.
func (*SpeedUpMarchRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{8}
}

func (x *SpeedUpMarchRequest) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *SpeedUpMarchRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SpeedUpMarchRequest) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

// SpeedUpMarchResponse 加速行军响应
type SpeedUpMarchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	NewArriveAt   int64                  `protobuf:"varint,2,opt,name=new_arrive_at,json=newArriveAt,proto3" json:"new_arrive_at,omitempty"` // 加速后新的预计到达时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedUpMarchResponse) Reset() {
	*x = SpeedUpMarchResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedUpMarchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedUpMarchResponse) ProtoMessage() {}

func (x *SpeedUpMarchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedUpMarchResponse.ProtoReflect.Descriptor instead.
func (*SpeedUpMarchResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{9}
}

func (x *SpeedUpMarchResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *SpeedUpMarchResponse) GetNewArriveAt() int64 {
	if x != nil {
		return x.NewArriveAt
	}
	return 0
}

// CreateRallyRequest 发起集结请求
// 路由: mapsvr.bigmapmarch.createrally
type CreateRallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPos     *Position              `protobuf:"bytes,1,opt,name=target_pos,json=targetPos,proto3" json:"target_pos,omitempty"`                                                     // 目标坐标
	TargetType    TargetType             `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=mapsvr.TargetType" json:"target_type,omitempty"`                          // 目标类型
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                                                       // 目标实体 ID
	WaitDuration  int64                  `protobuf:"varint,4,opt,name=wait_duration,json=waitDuration,proto3" json:"wait_duration,omitempty"`                                           // 等待成员加入的时间（秒）
	HeroIds       []int64                `protobuf:"varint,5,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`                                                   // 发起者派出的英雄
	Troops        map[int32]*TroopLevels `protobuf:"bytes,6,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 发起者派出的兵种
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRallyRequest) Reset() {
	*x = CreateRallyRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRallyRequest) ProtoMessage() {}

func (x *CreateRallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRallyRequest.ProtoReflect.Descriptor instead.
func (*CreateRallyRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRallyRequest) GetTargetPos() *Position {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

func (x *CreateRallyRequest) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *CreateRallyRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CreateRallyRequest) GetWaitDuration() int64 {
	if x != nil {
		return x.WaitDuration
	}
	return 0
}

func (x *CreateRallyRequest) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

func (x *CreateRallyRequest) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

// CreateRallyResponse 发起集结响应
type CreateRallyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Rally         *RallyInfo             `protobuf:"bytes,2,opt,name=rally,proto3" json:"rally,omitempty"` // 创建成功后的完整集结信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRallyResponse) Reset() {
	*x = CreateRallyResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRallyResponse) ProtoMessage() {}

func (x *CreateRallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRallyResponse.ProtoReflect.Descriptor instead.
func (*CreateRallyResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRallyResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *CreateRallyResponse) GetRally() *RallyInfo {
	if x != nil {
		return x.Rally
	}
	return nil
}

// JoinRallyRequest 加入集结请求
// 路由: mapsvr.bigmapmarch.joinrally
type JoinRallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RallyId       int64                  `protobuf:"varint,1,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`                                                          // 要加入的集结 ID
	HeroIds       []int64                `protobuf:"varint,2,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`                                                   // 派出的英雄
	Troops        map[int32]*TroopLevels `protobuf:"bytes,3,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 派出的兵种
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRallyRequest) Reset() {
	*x = JoinRallyRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRallyRequest) ProtoMessage() {}

func (x *JoinRallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRallyRequest.ProtoReflect.Descriptor instead.
func (*JoinRallyRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{12}
}

func (x *JoinRallyRequest) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

func (x *JoinRallyRequest) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

func (x *JoinRallyRequest) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

// JoinRallyResponse 加入集结响应
type JoinRallyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRallyResponse) Reset() {
	*x = JoinRallyResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRallyResponse) ProtoMessage() {}

func (x *JoinRallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRallyResponse.ProtoReflect.Descriptor instead.
func (*JoinRallyResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{13}
}

func (x *JoinRallyResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

// LaunchRallyRequest 手动提前发起集结（不等待倒计时结束）
// 路由: mapsvr.bigmapmarch.launchrally
type LaunchRallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RallyId       int64                  `protobuf:"varint,1,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRallyRequest) Reset() {
	*x = LaunchRallyRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRallyRequest) ProtoMessage() {}

func (x *LaunchRallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRallyRequest.ProtoReflect.Descriptor instead.
func (*LaunchRallyRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{14}
}

func (x *LaunchRallyRequest) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

// LaunchRallyResponse 手动发起集结响应
type LaunchRallyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRallyResponse) Reset() {
	*x = LaunchRallyResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRallyResponse) ProtoMessage() {}

func (x *LaunchRallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRallyResponse.ProtoReflect.Descriptor instead.
func (*LaunchRallyResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{15}
}

func (x *LaunchRallyResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

// CancelRallyRequest 取消集结请求
// 路由: mapsvr.bigmapmarch.cancelrally
type CancelRallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RallyId       int64                  `protobuf:"varint,1,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRallyRequest) Reset() {
	*x = CancelRallyRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRallyRequest) ProtoMessage() {}

func (x *CancelRallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRallyRequest.ProtoReflect.Descriptor instead.
func (*CancelRallyRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{16}
}

func (x *CancelRallyRequest) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

// CancelRallyResponse 取消集结响应
type CancelRallyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRallyResponse) Reset() {
	*x = CancelRallyResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRallyResponse) ProtoMessage() {}

func (x *CancelRallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRallyResponse.ProtoReflect.Descriptor instead.
func (*CancelRallyResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{17}
}

func (x *CancelRallyResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

// MarchCreateNotify 新行军创建通知
// 推送路由: bigmap.bigmapmarch.marchcreatenotify
// 推送范围: 所有在线大地图玩家（全服广播）
type MarchCreateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	March         *MarchInfo             `protobuf:"bytes,1,opt,name=march,proto3" json:"march,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarchCreateNotify) Reset() {
	*x = MarchCreateNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchCreateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchCreateNotify) ProtoMessage() {}

func (x *MarchCreateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchCreateNotify.ProtoReflect.Descriptor instead.
func (*MarchCreateNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{18}
}

func (x *MarchCreateNotify) GetMarch() *MarchInfo {
	if x != nil {
		return x.March
	}
	return nil
}

// MarchStateNotify 行军状态变更通知（到达/加速/取消等统一用此消息）
// 推送路由: bigmap.bigmapmarch.marchstatenotify
// 推送范围: 所有在线大地图玩家（全服广播）
// 客户端收到后用 march.march_id 匹配本地缓存并覆盖更新
type MarchStateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	March         *MarchInfo             `protobuf:"bytes,1,opt,name=march,proto3" json:"march,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarchStateNotify) Reset() {
	*x = MarchStateNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchStateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchStateNotify) ProtoMessage() {}

func (x *MarchStateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchStateNotify.ProtoReflect.Descriptor instead.
func (*MarchStateNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{19}
}

func (x *MarchStateNotify) GetMarch() *MarchInfo {
	if x != nil {
		return x.March
	}
	return nil
}

// MarchRemoveNotify 行军移除通知（回城到达或行军销毁）
// 推送路由: bigmap.bigmapmarch.marchremovenotify
// 推送范围: 所有在线大地图玩家（全服广播）
// 客户端收到后从本地缓存中删除该 march_id
type MarchRemoveNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarchRemoveNotify) Reset() {
	*x = MarchRemoveNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchRemoveNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchRemoveNotify) ProtoMessage() {}

func (x *MarchRemoveNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchRemoveNotify.ProtoReflect.Descriptor instead.
func (*MarchRemoveNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{20}
}

func (x *MarchRemoveNotify) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

// AllMarchSyncPush 玩家进入大地图时的全量同步
// 推送路由: bigmap.bigmapmarch.allmarchsyncpush
// 推送范围: 仅该玩家
// 包含当前所有活跃行军 + 本联盟活跃集结
type AllMarchSyncPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Marches       []*MarchInfo           `protobuf:"bytes,1,rep,name=marches,proto3" json:"marches,omitempty"` // 全服所有活跃行军
	Rallies       []*RallyInfo           `protobuf:"bytes,2,rep,name=rallies,proto3" json:"rallies,omitempty"` // 本联盟活跃集结
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllMarchSyncPush) Reset() {
	*x = AllMarchSyncPush{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllMarchSyncPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllMarchSyncPush) ProtoMessage() {}

func (x *AllMarchSyncPush) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllMarchSyncPush.ProtoReflect.Descriptor instead.
func (*AllMarchSyncPush) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{21}
}

func (x *AllMarchSyncPush) GetMarches() []*MarchInfo {
	if x != nil {
		return x.Marches
	}
	return nil
}

func (x *AllMarchSyncPush) GetRallies() []*RallyInfo {
	if x != nil {
		return x.Rallies
	}
	return nil
}

// BattleResultNotify 战斗结果通知
// 推送路由: bigmap.bigmapmarch.battleresultnotify
// 推送范围: 攻防双方玩家
type BattleResultNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"` // 触发战斗的行军 ID
	IsWin         bool                   `protobuf:"varint,2,opt,name=is_win,json=isWin,proto3" json:"is_win,omitempty"`       // 攻击方是否胜利
	Attacker      *FighterInfo           `protobuf:"bytes,3,opt,name=attacker,proto3" json:"attacker,omitempty"`               // 攻方战报详情
	Defencer      *FighterInfo           `protobuf:"bytes,4,opt,name=defencer,proto3" json:"defencer,omitempty"`               // 防方战报详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResultNotify) Reset() {
	*x = BattleResultNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResultNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResultNotify) ProtoMessage() {}

func (x *BattleResultNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResultNotify.ProtoReflect.Descriptor instead.
func (*BattleResultNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{22}
}

func (x *BattleResultNotify) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *BattleResultNotify) GetIsWin() bool {
	if x != nil {
		return x.IsWin
	}
	return false
}

func (x *BattleResultNotify) GetAttacker() *FighterInfo {
	if x != nil {
		return x.Attacker
	}
	return nil
}

func (x *BattleResultNotify) GetDefencer() *FighterInfo {
	if x != nil {
		return x.Defencer
	}
	return nil
}

// GatherResultNotify 采集结果通知
// 推送路由: bigmap.bigmapmarch.gatherresultnotify
// 推送范围: 采集玩家
type GatherResultNotify struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MarchId           int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	GatheredResources map[int32]int64        `protobuf:"bytes,2,rep,name=gathered_resources,json=gatheredResources,proto3" json:"gathered_resources,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 采集到的资源，key=资源类型ID, value=数量
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GatherResultNotify) Reset() {
	*x = GatherResultNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatherResultNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatherResultNotify) ProtoMessage() {}

func (x *GatherResultNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatherResultNotify.ProtoReflect.Descriptor instead.
func (*GatherResultNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{23}
}

func (x *GatherResultNotify) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *GatherResultNotify) GetGatheredResources() map[int32]int64 {
	if x != nil {
		return x.GatheredResources
	}
	return nil
}

// ScoutResultNotify 侦察报告通知
// 推送路由: bigmap.bigmapmarch.scoutresultnotify
// 推送范围: 侦察发起玩家
// proto3 零值字段不传输，客户端按 target_type 解读对应字段即可
type ScoutResultNotify struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MarchId    int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	TargetType TargetType             `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=mapsvr.TargetType" json:"target_type,omitempty"`
	TargetId   int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetPos  *Position              `protobuf:"bytes,4,opt,name=target_pos,json=targetPos,proto3" json:"target_pos,omitempty"`
	ConfigId   int32                  `protobuf:"varint,5,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"` // MapUnit 配置 ID
	// 资源点信息（target_type == RESOURCE）
	ResourceItemId    int32  `protobuf:"varint,10,opt,name=resource_item_id,json=resourceItemId,proto3" json:"resource_item_id,omitempty"`        // 资源物品 ID
	ResourceTotal     int64  `protobuf:"varint,11,opt,name=resource_total,json=resourceTotal,proto3" json:"resource_total,omitempty"`             // 资源总量
	ResourceRemaining int64  `protobuf:"varint,12,opt,name=resource_remaining,json=resourceRemaining,proto3" json:"resource_remaining,omitempty"` // 剩余量
	GatherPlayerId    string `protobuf:"bytes,13,opt,name=gather_player_id,json=gatherPlayerId,proto3" json:"gather_player_id,omitempty"`         // 正在采集的玩家 ID（空=无人采集）
	// 玩家城池信息（target_type == PLAYER_CITY）
	OwnerPlayerId string `protobuf:"bytes,20,opt,name=owner_player_id,json=ownerPlayerId,proto3" json:"owner_player_id,omitempty"` // 城主玩家 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoutResultNotify) Reset() {
	*x = ScoutResultNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoutResultNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutResultNotify) ProtoMessage() {}

func (x *ScoutResultNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutResultNotify.ProtoReflect.Descriptor instead.
func (*ScoutResultNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{24}
}

func (x *ScoutResultNotify) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *ScoutResultNotify) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *ScoutResultNotify) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ScoutResultNotify) GetTargetPos() *Position {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

func (x *ScoutResultNotify) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ScoutResultNotify) GetResourceItemId() int32 {
	if x != nil {
		return x.ResourceItemId
	}
	return 0
}

func (x *ScoutResultNotify) GetResourceTotal() int64 {
	if x != nil {
		return x.ResourceTotal
	}
	return 0
}

func (x *ScoutResultNotify) GetResourceRemaining() int64 {
	if x != nil {
		return x.ResourceRemaining
	}
	return 0
}

func (x *ScoutResultNotify) GetGatherPlayerId() string {
	if x != nil {
		return x.GatherPlayerId
	}
	return ""
}

func (x *ScoutResultNotify) GetOwnerPlayerId() string {
	if x != nil {
		return x.OwnerPlayerId
	}
	return ""
}

// RallyCreateNotify 集结创建通知
// 推送路由: bigmap.bigmapmarch.rallycreatenotify
// 推送范围: 联盟全体成员
type RallyCreateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rally         *RallyInfo             `protobuf:"bytes,1,opt,name=rally,proto3" json:"rally,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RallyCreateNotify) Reset() {
	*x = RallyCreateNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RallyCreateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RallyCreateNotify) ProtoMessage() {}

func (x *RallyCreateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RallyCreateNotify.ProtoReflect.Descriptor instead.
func (*RallyCreateNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{25}
}

func (x *RallyCreateNotify) GetRally() *RallyInfo {
	if x != nil {
		return x.Rally
	}
	return nil
}

// RallyUpdateNotify 集结变更通知（成员加入/手动发起/取消等）
// 推送路由: bigmap.bigmapmarch.rallyupdatenotify
// 推送范围: 联盟全体成员
type RallyUpdateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rally         *RallyInfo             `protobuf:"bytes,1,opt,name=rally,proto3" json:"rally,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RallyUpdateNotify) Reset() {
	*x = RallyUpdateNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RallyUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RallyUpdateNotify) ProtoMessage() {}

func (x *RallyUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RallyUpdateNotify.ProtoReflect.Descriptor instead.
func (*RallyUpdateNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{26}
}

func (x *RallyUpdateNotify) GetRally() *RallyInfo {
	if x != nil {
		return x.Rally
	}
	return nil
}

var File_mapsvr_bigmapmarch_proto protoreflect.FileDescriptor

const file_mapsvr_bigmapmarch_proto_rawDesc = "" +
	"\n" +
	"\x18mapsvr/bigmapmarch.proto\x12\x06mapsvr\x1a\x18common/types/types.proto\x1a\x13mapsvr/bigmap.proto\x1a\x19mapsvr/bigmapbattle.proto\"\x96\x01\n" +
	"\vTroopLevels\x12G\n" +
	"\flevel_counts\x18\x01 \x03(\v2$.mapsvr.TroopLevels.LevelCountsEntryR\vlevelCounts\x1a>\n" +
	"\x10LevelCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xe1\x04\n" +
	"\tMarchInfo\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x120\n" +
	"\n" +
	"march_type\x18\x03 \x01(\x0e2\x11.mapsvr.MarchTypeR\tmarchType\x12(\n" +
	"\x05state\x18\x04 \x01(\x0e2\x12.mapsvr.MarchStateR\x05state\x12+\n" +
	"\bfrom_pos\x18\x05 \x01(\v2\x10.mapsvr.PositionR\afromPos\x12'\n" +
	"\x06to_pos\x18\x06 \x01(\v2\x10.mapsvr.PositionR\x05toPos\x12\x19\n" +
	"\bstart_at\x18\a \x01(\x03R\astartAt\x12\x1b\n" +
	"\tarrive_at\x18\b \x01(\x03R\barriveAt\x123\n" +
	"\vtarget_type\x18\t \x01(\x0e2\x12.mapsvr.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\n" +
	" \x01(\x03R\btargetId\x12\x19\n" +
	"\bhero_ids\x18\v \x03(\x03R\aheroIds\x125\n" +
	"\x06troops\x18\f \x03(\v2\x1d.mapsvr.MarchInfo.TroopsEntryR\x06troops\x12\x19\n" +
	"\brally_id\x18\r \x01(\x03R\arallyId\x12#\n" +
	"\rexpedition_id\x18\x0e \x01(\x03R\fexpeditionId\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x0fRallyMemberInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12;\n" +
	"\x06troops\x18\x02 \x03(\v2#.mapsvr.RallyMemberInfo.TroopsEntryR\x06troops\x12\x19\n" +
	"\bhero_ids\x18\x03 \x03(\x03R\aheroIds\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\"\xa1\x03\n" +
	"\tRallyInfo\x12\x19\n" +
	"\brally_id\x18\x01 \x01(\x03R\arallyId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x1f\n" +
	"\valliance_id\x18\x03 \x01(\tR\n" +
	"allianceId\x12/\n" +
	"\n" +
	"target_pos\x18\x04 \x01(\v2\x10.mapsvr.PositionR\ttargetPos\x123\n" +
	"\vtarget_type\x18\x05 \x01(\x0e2\x12.mapsvr.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\x03R\btargetId\x12!\n" +
	"\fmax_capacity\x18\a \x01(\x03R\vmaxCapacity\x12\x1b\n" +
	"\tcreate_at\x18\b \x01(\x03R\bcreateAt\x12\x1b\n" +
	"\tlaunch_at\x18\t \x01(\x03R\blaunchAt\x12(\n" +
	"\x05state\x18\n" +
	" \x01(\x0e2\x12.mapsvr.RallyStateR\x05state\x121\n" +
	"\amembers\x18\v \x03(\v2\x17.mapsvr.RallyMemberInfoR\amembers\"\xea\x02\n" +
	"\x11StartMarchRequest\x120\n" +
	"\n" +
	"march_type\x18\x01 \x01(\x0e2\x11.mapsvr.MarchTypeR\tmarchType\x12'\n" +
	"\x06to_pos\x18\x02 \x01(\v2\x10.mapsvr.PositionR\x05toPos\x123\n" +
	"\vtarget_type\x18\x03 \x01(\x0e2\x12.mapsvr.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x03R\btargetId\x12\x19\n" +
	"\bhero_ids\x18\x05 \x03(\x03R\aheroIds\x12=\n" +
	"\x06troops\x18\x06 \x03(\v2%.mapsvr.StartMarchRequest.TroopsEntryR\x06troops\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\"d\n" +
	"\x12StartMarchResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12'\n" +
	"\x05march\x18\x02 \x01(\v2\x11.mapsvr.MarchInfoR\x05march\"/\n" +
	"\x12CancelMarchRequest\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\"<\n" +
	"\x13CancelMarchResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"d\n" +
	"\x13SpeedUpMarchRequest\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x03 \x01(\x05R\aitemNum\"a\n" +
	"\x14SpeedUpMarchResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12\"\n" +
	"\rnew_arrive_at\x18\x02 \x01(\x03R\vnewArriveAt\"\xe7\x02\n" +
	"\x12CreateRallyRequest\x12/\n" +
	"\n" +
	"target_pos\x18\x01 \x01(\v2\x10.mapsvr.PositionR\ttargetPos\x123\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2\x12.mapsvr.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12#\n" +
	"\rwait_duration\x18\x04 \x01(\x03R\fwaitDuration\x12\x19\n" +
	"\bhero_ids\x18\x05 \x03(\x03R\aheroIds\x12>\n" +
	"\x06troops\x18\x06 \x03(\v2&.mapsvr.CreateRallyRequest.TroopsEntryR\x06troops\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\"e\n" +
	"\x13CreateRallyResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12'\n" +
	"\x05rally\x18\x02 \x01(\v2\x11.mapsvr.RallyInfoR\x05rally\"\xd6\x01\n" +
	"\x10JoinRallyRequest\x12\x19\n" +
	"\brally_id\x18\x01 \x01(\x03R\arallyId\x12\x19\n" +
	"\bhero_ids\x18\x02 \x03(\x03R\aheroIds\x12<\n" +
	"\x06troops\x18\x03 \x03(\v2$.mapsvr.JoinRallyRequest.TroopsEntryR\x06troops\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\":\n" +
	"\x11JoinRallyResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"/\n" +
	"\x12LaunchRallyRequest\x12\x19\n" +
	"\brally_id\x18\x01 \x01(\x03R\arallyId\"<\n" +
	"\x13LaunchRallyResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"/\n" +
	"\x12CancelRallyRequest\x12\x19\n" +
	"\brally_id\x18\x01 \x01(\x03R\arallyId\"<\n" +
	"\x13CancelRallyResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"<\n" +
	"\x11MarchCreateNotify\x12'\n" +
	"\x05march\x18\x01 \x01(\v2\x11.mapsvr.MarchInfoR\x05march\";\n" +
	"\x10MarchStateNotify\x12'\n" +
	"\x05march\x18\x01 \x01(\v2\x11.mapsvr.MarchInfoR\x05march\".\n" +
	"\x11MarchRemoveNotify\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\"l\n" +
	"\x10AllMarchSyncPush\x12+\n" +
	"\amarches\x18\x01 \x03(\v2\x11.mapsvr.MarchInfoR\amarches\x12+\n" +
	"\arallies\x18\x02 \x03(\v2\x11.mapsvr.RallyInfoR\arallies\"\xa8\x01\n" +
	"\x12BattleResultNotify\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\x12\x15\n" +
	"\x06is_win\x18\x02 \x01(\bR\x05isWin\x12/\n" +
	"\battacker\x18\x03 \x01(\v2\x13.mapsvr.FighterInfoR\battacker\x12/\n" +
	"\bdefencer\x18\x04 \x01(\v2\x13.mapsvr.FighterInfoR\bdefencer\"\xd7\x01\n" +
	"\x12GatherResultNotify\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\x12`\n" +
	"\x12gathered_resources\x18\x02 \x03(\v21.mapsvr.GatherResultNotify.GatheredResourcesEntryR\x11gatheredResources\x1aD\n" +
	"\x16GatheredResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xa0\x03\n" +
	"\x11ScoutResultNotify\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\x123\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2\x12.mapsvr.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12/\n" +
	"\n" +
	"target_pos\x18\x04 \x01(\v2\x10.mapsvr.PositionR\ttargetPos\x12\x1b\n" +
	"\tconfig_id\x18\x05 \x01(\x05R\bconfigId\x12(\n" +
	"\x10resource_item_id\x18\n" +
	" \x01(\x05R\x0eresourceItemId\x12%\n" +
	"\x0eresource_total\x18\v \x01(\x03R\rresourceTotal\x12-\n" +
	"\x12resource_remaining\x18\f \x01(\x03R\x11resourceRemaining\x12(\n" +
	"\x10gather_player_id\x18\r \x01(\tR\x0egatherPlayerId\x12&\n" +
	"\x0fowner_player_id\x18\x14 \x01(\tR\rownerPlayerId\"<\n" +
	"\x11RallyCreateNotify\x12'\n" +
	"\x05rally\x18\x01 \x01(\v2\x11.mapsvr.RallyInfoR\x05rally\"<\n" +
	"\x11RallyUpdateNotify\x12'\n" +
	"\x05rally\x18\x01 \x01(\v2\x11.mapsvr.RallyInfoR\x05rally*N\n" +
	"\tTroopType\x12\x1a\n" +
	"\x16TROOP_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bINFANTRY\x10\x01\x12\v\n" +
	"\aCAVALRY\x10\x02\x12\n" +
	"\n" +
	"\x06ARCHER\x10\x03*\xcd\x01\n" +
	"\tMarchType\x12\x1a\n" +
	"\x16MARCH_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MARCH_TYPE_ATTACK\x10\x01\x12\x15\n" +
	"\x11MARCH_TYPE_GATHER\x10\x02\x12\x14\n" +
	"\x10MARCH_TYPE_SCOUT\x10\x03\x12\x14\n" +
	"\x10MARCH_TYPE_RALLY\x10\x04\x12\x18\n" +
	"\x14MARCH_TYPE_REINFORCE\x10\x05\x12\x15\n" +
	"\x11MARCH_TYPE_RETURN\x10\x06\x12\x19\n" +
	"\x15MARCH_TYPE_RALLY_LEAD\x10\a*\xc8\x01\n" +
	"\n" +
	"MarchState\x12\x1b\n" +
	"\x17MARCH_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MARCH_STATE_MARCHING\x10\x01\x12\x18\n" +
	"\x14MARCH_STATE_FIGHTING\x10\x02\x12\x19\n" +
	"\x15MARCH_STATE_GATHERING\x10\x03\x12\x19\n" +
	"\x15MARCH_STATE_STATIONED\x10\x04\x12\x18\n" +
	"\x14MARCH_STATE_SCOUTING\x10\x05\x12\x19\n" +
	"\x15MARCH_STATE_RETURNING\x10\x06*\x93\x01\n" +
	"\n" +
	"TargetType\x12\x1b\n" +
	"\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TARGET_TYPE_PLAYER_CITY\x10\x01\x12\x17\n" +
	"\x13TARGET_TYPE_MONSTER\x10\x02\x12\x18\n" +
	"\x14TARGET_TYPE_RESOURCE\x10\x03\x12\x18\n" +
	"\x14TARGET_TYPE_ALLIANCE\x10\x04*\x8d\x01\n" +
	"\n" +
	"RallyState\x12\x1b\n" +
	"\x17RALLY_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RALLY_STATE_WAITING\x10\x01\x12\x18\n" +
	"\x14RALLY_STATE_MARCHING\x10\x02\x12\x18\n" +
	"\x14RALLY_STATE_FIGHTING\x10\x03\x12\x15\n" +
	"\x11RALLY_STATE_ENDED\x10\x04B.Z,pitaya-game/protos/protobuf/pb/golang/mapsvrb\x06proto3"

var (
	file_mapsvr_bigmapmarch_proto_rawDescOnce sync.Once
	file_mapsvr_bigmapmarch_proto_rawDescData []byte
)

func file_mapsvr_bigmapmarch_proto_rawDescGZIP() []byte {
	file_mapsvr_bigmapmarch_proto_rawDescOnce.Do(func() {
		file_mapsvr_bigmapmarch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mapsvr_bigmapmarch_proto_rawDesc), len(file_mapsvr_bigmapmarch_proto_rawDesc)))
	})
	return file_mapsvr_bigmapmarch_proto_rawDescData
}

var file_mapsvr_bigmapmarch_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_mapsvr_bigmapmarch_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_mapsvr_bigmapmarch_proto_goTypes = []any{
	(TroopType)(0),               // 0: mapsvr.TroopType
	(MarchType)(0),               // 1: mapsvr.MarchType
	(MarchState)(0),              // 2: mapsvr.MarchState
	(TargetType)(0),              // 3: mapsvr.TargetType
	(RallyState)(0),              // 4: mapsvr.RallyState
	(*TroopLevels)(nil),          // 5: mapsvr.TroopLevels
	(*MarchInfo)(nil),            // 6: mapsvr.MarchInfo
	(*RallyMemberInfo)(nil),      // 7: mapsvr.RallyMemberInfo
	(*RallyInfo)(nil),            // 8: mapsvr.RallyInfo
	(*StartMarchRequest)(nil),    // 9: mapsvr.StartMarchRequest
	(*StartMarchResponse)(nil),   // 10: mapsvr.StartMarchResponse
	(*CancelMarchRequest)(nil),   // 11: mapsvr.CancelMarchRequest
	(*CancelMarchResponse)(nil),  // 12: mapsvr.CancelMarchResponse
	(*SpeedUpMarchRequest)(nil),  // 13: mapsvr.SpeedUpMarchRequest
	(*SpeedUpMarchResponse)(nil), // 14: mapsvr.SpeedUpMarchResponse
	(*CreateRallyRequest)(nil),   // 15: mapsvr.CreateRallyRequest
	(*CreateRallyResponse)(nil),  // 16: mapsvr.CreateRallyResponse
	(*JoinRallyRequest)(nil),     // 17: mapsvr.JoinRallyRequest
	(*JoinRallyResponse)(nil),    // 18: mapsvr.JoinRallyResponse
	(*LaunchRallyRequest)(nil),   // 19: mapsvr.LaunchRallyRequest
	(*LaunchRallyResponse)(nil),  // 20: mapsvr.LaunchRallyResponse
	(*CancelRallyRequest)(nil),   // 21: mapsvr.CancelRallyRequest
	(*CancelRallyResponse)(nil),  // 22: mapsvr.CancelRallyResponse
	(*MarchCreateNotify)(nil),    // 23: mapsvr.MarchCreateNotify
	(*MarchStateNotify)(nil),     // 24: mapsvr.MarchStateNotify
	(*MarchRemoveNotify)(nil),    // 25: mapsvr.MarchRemoveNotify
	(*AllMarchSyncPush)(nil),     // 26: mapsvr.AllMarchSyncPush
	(*BattleResultNotify)(nil),   // 27: mapsvr.BattleResultNotify
	(*GatherResultNotify)(nil),   // 28: mapsvr.GatherResultNotify
	(*ScoutResultNotify)(nil),    // 29: mapsvr.ScoutResultNotify
	(*RallyCreateNotify)(nil),    // 30: mapsvr.RallyCreateNotify
	(*RallyUpdateNotify)(nil),    // 31: mapsvr.RallyUpdateNotify
	nil,                          // 32: mapsvr.TroopLevels.LevelCountsEntry
	nil,                          // 33: mapsvr.MarchInfo.TroopsEntry
	nil,                          // 34: mapsvr.RallyMemberInfo.TroopsEntry
	nil,                          // 35: mapsvr.StartMarchRequest.TroopsEntry
	nil,                          // 36: mapsvr.CreateRallyRequest.TroopsEntry
	nil,                          // 37: mapsvr.JoinRallyRequest.TroopsEntry
	nil,                          // 38: mapsvr.GatherResultNotify.GatheredResourcesEntry
	(*Position)(nil),             // 39: mapsvr.Position
	(*types.CommonResp)(nil),     // 40: types.CommonResp
	(*FighterInfo)(nil),          // 41: mapsvr.FighterInfo
}
var file_mapsvr_bigmapmarch_proto_depIdxs = []int32{
	32, // 0: mapsvr.TroopLevels.level_counts:type_name -> mapsvr.TroopLevels.LevelCountsEntry
	1,  // 1: mapsvr.MarchInfo.march_type:type_name -> mapsvr.MarchType
	2,  // 2: mapsvr.MarchInfo.state:type_name -> mapsvr.MarchState
	39, // 3: mapsvr.MarchInfo.from_pos:type_name -> mapsvr.Position
	39, // 4: mapsvr.MarchInfo.to_pos:type_name -> mapsvr.Position
	3,  // 5: mapsvr.MarchInfo.target_type:type_name -> mapsvr.TargetType
	33, // 6: mapsvr.MarchInfo.troops:type_name -> mapsvr.MarchInfo.TroopsEntry
	34, // 7: mapsvr.RallyMemberInfo.troops:type_name -> mapsvr.RallyMemberInfo.TroopsEntry
	39, // 8: mapsvr.RallyInfo.target_pos:type_name -> mapsvr.Position
	3,  // 9: mapsvr.RallyInfo.target_type:type_name -> mapsvr.TargetType
	4,  // 10: mapsvr.RallyInfo.state:type_name -> mapsvr.RallyState
	7,  // 11: mapsvr.RallyInfo.members:type_name -> mapsvr.RallyMemberInfo
	1,  // 12: mapsvr.StartMarchRequest.march_type:type_name -> mapsvr.MarchType
	39, // 13: mapsvr.StartMarchRequest.to_pos:type_name -> mapsvr.Position
	3,  // 14: mapsvr.StartMarchRequest.target_type:type_name -> mapsvr.TargetType
	35, // 15: mapsvr.StartMarchRequest.troops:type_name -> mapsvr.StartMarchRequest.TroopsEntry
	40, // 16: mapsvr.StartMarchResponse.resp:type_name -> types.CommonResp
	6,  // 17: mapsvr.StartMarchResponse.march:type_name -> mapsvr.MarchInfo
	40, // 18: mapsvr.CancelMarchResponse.resp:type_name -> types.CommonResp
	40, // 19: mapsvr.SpeedUpMarchResponse.resp:type_name -> types.CommonResp
	39, // 20: mapsvr.CreateRallyRequest.target_pos:type_name -> mapsvr.Position
	3,  // 21: mapsvr.CreateRallyRequest.target_type:type_name -> mapsvr.TargetType
	36, // 22: mapsvr.CreateRallyRequest.troops:type_name -> mapsvr.CreateRallyRequest.TroopsEntry
	40, // 23: mapsvr.CreateRallyResponse.resp:type_name -> types.CommonResp
	8,  // 24: mapsvr.CreateRallyResponse.rally:type_name -> mapsvr.RallyInfo
	37, // 25: mapsvr.JoinRallyRequest.troops:type_name -> mapsvr.JoinRallyRequest.TroopsEntry
	40, // 26: mapsvr.JoinRallyResponse.resp:type_name -> types.CommonResp
	40, // 27: mapsvr.LaunchRallyResponse.resp:type_name -> types.CommonResp
	40, // 28: mapsvr.CancelRallyResponse.resp:type_name -> types.CommonResp
	6,  // 29: mapsvr.MarchCreateNotify.march:type_name -> mapsvr.MarchInfo
	6,  // 30: mapsvr.MarchStateNotify.march:type_name -> mapsvr.MarchInfo
	6,  // 31: mapsvr.AllMarchSyncPush.marches:type_name -> mapsvr.MarchInfo
	8,  // 32: mapsvr.AllMarchSyncPush.rallies:type_name -> mapsvr.RallyInfo
	41, // 33: mapsvr.BattleResultNotify.attacker:type_name -> mapsvr.FighterInfo
	41, // 34: mapsvr.BattleResultNotify.defencer:type_name -> mapsvr.FighterInfo
	38, // 35: mapsvr.GatherResultNotify.gathered_resources:type_name -> mapsvr.GatherResultNotify.GatheredResourcesEntry
	3,  // 36: mapsvr.ScoutResultNotify.target_type:type_name -> mapsvr.TargetType
	39, // 37: mapsvr.ScoutResultNotify.target_pos:type_name -> mapsvr.Position
	8,  // 38: mapsvr.RallyCreateNotify.rally:type_name -> mapsvr.RallyInfo
	8,  // 39: mapsvr.RallyUpdateNotify.rally:type_name -> mapsvr.RallyInfo
	5,  // 40: mapsvr.MarchInfo.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	5,  // 41: mapsvr.RallyMemberInfo.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	5,  // 42: mapsvr.StartMarchRequest.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	5,  // 43: mapsvr.CreateRallyRequest.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	5,  // 44: mapsvr.JoinRallyRequest.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	45, // [45:45] is the sub-list for method output_type
	45, // [45:45] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_mapsvr_bigmapmarch_proto_init() }
func file_mapsvr_bigmapmarch_proto_init() {
	if File_mapsvr_bigmapmarch_proto != nil {
		return
	}
	file_mapsvr_bigmap_proto_init()
	file_mapsvr_bigmapbattle_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mapsvr_bigmapmarch_proto_rawDesc), len(file_mapsvr_bigmapmarch_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapsvr_bigmapmarch_proto_goTypes,
		DependencyIndexes: file_mapsvr_bigmapmarch_proto_depIdxs,
		EnumInfos:         file_mapsvr_bigmapmarch_proto_enumTypes,
		MessageInfos:      file_mapsvr_bigmapmarch_proto_msgTypes,
	}.Build()
	File_mapsvr_bigmapmarch_proto = out.File
	file_mapsvr_bigmapmarch_proto_goTypes = nil
	file_mapsvr_bigmapmarch_proto_depIdxs = nil
}
