syntax = "proto3";

package gamesvr;

option go_package = "pitaya-game/protos/protobuf/pb/golang/gamesvr;gamesvrpb";
option csharp_namespace = "PitayaGame.GameSvr";

import "common/types/types.proto";

// ============================================================================
// 兵营系统协议定义
// 微服务名称：gamesvr.mercenary
// 包括：
// ============================================================================

// ========== 数据结构 ==========


message MercenaryTimeWork {
  int32 work_type = 50;                 //工作类型 1 训练 2 晋升  3 轻伤 4 重伤
  int64 work_begin_time=51;      //开始时间
  int64 work_end_time = 52;       // 完成时间
  int32 num=53; //数量
}

message MercenaryTypeNum {
  int32 num=1; //数量
  int32 type=2; //类型 0= 正常 1 训练 2 晋升（直接解锁最高级） 3 轻伤 4 重伤
}



//雇佣兵数据
message MercenaryBaseData {
  int32 mercenary_config_id = 1;        // 配置表ID
  MercenaryTypeNum type_num=2; //数量
}


// 雇佣兵数据
message MercenaryData {
  MercenaryBaseData info=1; //基础信息
  optional MercenaryTimeWork time_work = 5;
}


// ========== 获取我的雇佣兵 ==========

// 获取我的所有请求
message GetMyMercenaryRequest {
  // 无需参数，从 Session 获取 user_id
}

// 获取我的所有响应
message GetMyMercenaryResponse {
  types.CommonResp resp = 1;
  repeated MercenaryData mercenary = 3;
  int64 server_time=30;  //服务器时间
}

//获取单个兵种的数据
message GetMercenaryInfoRequest {
  int32 mercenary_config_id = 1;        // 配置表ID
}

message GetMercenaryInfoResponse {
  types.CommonResp resp = 1;
  MercenaryData mercenary = 3;
  int64 server_time=30;  //服务器时间
}


// ========== 雇佣兵训练 ==========

// 雇佣兵训练请求
message TrainingMercenaryRequest {
    int32 mercenary_config_id = 1;        // 配置表ID
    int64 num=2; //数量
}

// 雇佣兵训练立即完成请求
message TrainingMercenaryKoRequest {
    int32 mercenary_config_id = 1;
}


// 雇佣兵训练响应
message TrainingMercenaryResponse {
  types.CommonResp resp = 1;
  MercenaryTimeWork work_time=2;
}

// ========== 雇佣兵晋升 ==========

// 晋升请求
message UpgradeMercenaryRequest {
    int32 mercenary_config_id = 1;        // 配置表ID
    int64 num=2; //数量
}

// 晋升请求立即完成
message UpgradeMercenaryKoRequest {
    int32 mercenary_config_id = 1;        // 配置表ID
}


// 晋升响应
message UpgradeMercenaryResponse {
  types.CommonResp resp = 1;
  MercenaryTimeWork work_time=2;
}


// ========== 雇佣兵加速 立即完成 取消 ==========

// 加速
message WorkTurboMercenaryRequest {
   int64 mercenary_config_id = 1;
}

message WorkTurboMercenaryResponse {
  types.CommonResp resp = 1;
  MercenaryTimeWork work_time=2;
}

// 立即完成
message WorkKoMercenaryRequest {
   int32 mercenary_config_id = 1;
}

//取消
message WorkCancelMercenaryRequest {
   int32 mercenary_config_id = 1;
}

message WorkCancelMercenaryResponse {
  types.CommonResp resp = 1;
  MercenaryData mercenary = 3;
  int64 server_time=30;  //服务器时间
}

// ========== 出征 ==========

message ToWarMercenaryRemoteRequest {
  string user_id=1;//哪个玩家
  repeated MercenaryBaseData mercenary=2; // 派出的兵种/数量 类型都是0
}

message ToWarMercenaryResponse {
  types.CommonResp resp = 1;
}

// 训练/升级完成后，转成正式
message ToFormalMercenaryRequest {
  int32 mercenary_config_id = 1; //配置表ID
}


//战斗结束还回兵
message ToHomeMercenaryRemoteRequest {
  string user_id=1;//哪个玩家
  repeated MercenaryBaseData mercenary=2;   //还回来的兵 类型就好几种
}

message ToHomeMercenaryRemoteResponse {
  types.CommonResp resp = 1;
}


// ========== 删除(测试用) ==========

// 删除请求 测试用
message DestroyMercenaryRequest {
  int32 mercenary_config_id = 1;
  int32 num=2;
}

// 删除响应
message DestroyMercenaryResponse {
  types.CommonResp resp = 1;
}

//增加
message NewMercenaryRequest {
  int32 mercenary_config_id = 1;
  int32 num=2;
}

// 增加响应
message NewMercenaryResponse {
  types.CommonResp resp = 1;
}
