syntax = "proto3";

package gamesvr;

option go_package = "pitaya-game/protos/protobuf/pb/golang/gamesvr;gamesvrpb";
option csharp_namespace = "PitayaGame.GameSvr";

import "common/types/types.proto";

// ============================================================================
// 兵营系统协议定义
// 微服务名称：gamesvr.mercenary
// 包括：
// ============================================================================

// ========== 数据结构 ==========


message MercenaryTimeWork {
  int32 work_type = 50;                 //工作类型 1 训练 2 升级
  int64 work_begin_time=51;      //开始时间
  int64 work_end_time = 52;       // 完成时间
  int32 num=53; //数量
}

//雇佣兵数据
message MercenaryBaseData {
  int32 mercenary_config_id = 1;        // 配置表ID
  int32 num=2; //数量
}


// 雇佣兵数据
message MercenaryData {
  MercenaryBaseData info=1; //基础信息
  optional MercenaryTimeWork time_work = 5;           // 训练 升级
}


// ========== 获取我的雇佣兵 ==========

// 获取我的所有请求
message GetMyMercenaryRequest {
  // 无需参数，从 Session 获取 user_id
}

// 获取我的所有响应
message GetMyMercenaryResponse {
  types.CommonResp resp = 1;
  int64 server_time=2;  //服务器时间
  repeated MercenaryData mercenary = 3;
}


// ========== 雇佣兵训练 ==========

// 雇佣兵训练请求
message TrainingMercenaryRequest {
    MercenaryBaseData mercenary=1;
}

// 雇佣兵训练立即完成请求
message TrainingMercenaryKoRequest {
    MercenaryBaseData mercenary=1;
}


// 雇佣兵训练响应
message TrainingMercenaryResponse {
  types.CommonResp resp = 1;
  MercenaryData mercenary_data = 2;
}

// ========== 雇佣兵升级 ==========

// 升级请求
message UpgradeMercenaryRequest {
    MercenaryBaseData mercenary=1;
}

// 升级请求立即完成
message UpgradeMercenaryKoRequest {
    MercenaryBaseData mercenary=1;
}


// 升级响应
message UpgradeMercenaryResponse {
  types.CommonResp resp = 1;
  MercenaryData mercenary_data = 2;
}


// ========== 雇佣兵加速 立即完成 取消 ==========

// 加速
message WorkTurboMercenaryRequest {
   int64 mercenary_config_id = 1;
}

message WorkTurboMercenaryResponse {
  types.CommonResp resp = 1;
  MercenaryData mercenary_data = 2;
}

// 立即完成
message WorkKoMercenaryRequest {
   int32 mercenary_config_id = 1;
}

//取消
message WorkCancelMercenaryRequest {
   int32 mercenary_config_id = 1;
}

message WorkCancelMercenaryResponse {
  types.CommonResp resp = 1;
}

// ========== 出征 ==========

message ToWarMercenaryRequest {
  repeated MercenaryBaseData mercenary=1;
}

message ToWarMercenaryResponse {
  types.CommonResp resp = 1;
}



// ========== 删除(测试用) ==========

// 删除请求 测试用
message DestroyMercenaryRequest {
  int32 mercenary_config_id = 1;
  int32 num=2;
}

// 删除响应
message DestroyMercenaryResponse {
  types.CommonResp resp = 1;
}
