// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: gamesvr/mercenary.proto

package gamesvrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MercenaryTimeWork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkType      int32                  `protobuf:"varint,50,opt,name=work_type,json=workType,proto3" json:"work_type,omitempty"`                  //工作类型 0 空闲 1 升级 2 生产
	WorkBeginTime int64                  `protobuf:"varint,51,opt,name=work_begin_time,json=workBeginTime,proto3" json:"work_begin_time,omitempty"` //开始时间
	WorkEndTime   int64                  `protobuf:"varint,52,opt,name=work_end_time,json=workEndTime,proto3" json:"work_end_time,omitempty"`       // 完成时间
	Num           int32                  `protobuf:"varint,53,opt,name=num,proto3" json:"num,omitempty"`                                            //数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MercenaryTimeWork) Reset() {
	*x = MercenaryTimeWork{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MercenaryTimeWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MercenaryTimeWork) ProtoMessage() {}

func (x *MercenaryTimeWork) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MercenaryTimeWork.ProtoReflect.Descriptor instead.
func (*MercenaryTimeWork) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{0}
}

func (x *MercenaryTimeWork) GetWorkType() int32 {
	if x != nil {
		return x.WorkType
	}
	return 0
}

func (x *MercenaryTimeWork) GetWorkBeginTime() int64 {
	if x != nil {
		return x.WorkBeginTime
	}
	return 0
}

func (x *MercenaryTimeWork) GetWorkEndTime() int64 {
	if x != nil {
		return x.WorkEndTime
	}
	return 0
}

func (x *MercenaryTimeWork) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 雇佣兵数据
type MercenaryData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MercenaryId       int64                  `protobuf:"varint,1,opt,name=mercenary_id,json=mercenaryId,proto3" json:"mercenary_id,omitempty"`                     // 建筑ID（实例ID）
	MercenaryConfigId int32                  `protobuf:"varint,2,opt,name=mercenary_config_id,json=mercenaryConfigId,proto3" json:"mercenary_config_id,omitempty"` // 建筑配置表ID（对应Builds表的ID）
	Level             int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                                    //等级
	Num               int32                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`                                                        //数量
	TimeWork          *MercenaryTimeWork     `protobuf:"bytes,5,opt,name=time_work,json=timeWork,proto3" json:"time_work,omitempty"`                               // 时间工作数据
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MercenaryData) Reset() {
	*x = MercenaryData{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MercenaryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MercenaryData) ProtoMessage() {}

func (x *MercenaryData) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MercenaryData.ProtoReflect.Descriptor instead.
func (*MercenaryData) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{1}
}

func (x *MercenaryData) GetMercenaryId() int64 {
	if x != nil {
		return x.MercenaryId
	}
	return 0
}

func (x *MercenaryData) GetMercenaryConfigId() int32 {
	if x != nil {
		return x.MercenaryConfigId
	}
	return 0
}

func (x *MercenaryData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MercenaryData) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *MercenaryData) GetTimeWork() *MercenaryTimeWork {
	if x != nil {
		return x.TimeWork
	}
	return nil
}

// 获取我的所有请求
type GetMyMercenaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyMercenaryRequest) Reset() {
	*x = GetMyMercenaryRequest{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyMercenaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyMercenaryRequest) ProtoMessage() {}

func (x *GetMyMercenaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyMercenaryRequest.ProtoReflect.Descriptor instead.
func (*GetMyMercenaryRequest) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{2}
}

// 获取我的所有响应
type GetMyMercenaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Mercenary     []*MercenaryData       `protobuf:"bytes,2,rep,name=mercenary,proto3" json:"mercenary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyMercenaryResponse) Reset() {
	*x = GetMyMercenaryResponse{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyMercenaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyMercenaryResponse) ProtoMessage() {}

func (x *GetMyMercenaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyMercenaryResponse.ProtoReflect.Descriptor instead.
func (*GetMyMercenaryResponse) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyMercenaryResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetMyMercenaryResponse) GetMercenary() []*MercenaryData {
	if x != nil {
		return x.Mercenary
	}
	return nil
}

// 雇佣兵训练请求
type TrainingMercenaryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MercenaryConfigId int32                  `protobuf:"varint,1,opt,name=mercenary_config_id,json=mercenaryConfigId,proto3" json:"mercenary_config_id,omitempty"` // 建筑配置表ID，user_id 从 Session 获取
	Num               int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                                                        // 数量
	Type              int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                                                      // 方式 0 消耗时间 1 立即完成
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrainingMercenaryRequest) Reset() {
	*x = TrainingMercenaryRequest{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingMercenaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingMercenaryRequest) ProtoMessage() {}

func (x *TrainingMercenaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingMercenaryRequest.ProtoReflect.Descriptor instead.
func (*TrainingMercenaryRequest) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{4}
}

func (x *TrainingMercenaryRequest) GetMercenaryConfigId() int32 {
	if x != nil {
		return x.MercenaryConfigId
	}
	return 0
}

func (x *TrainingMercenaryRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *TrainingMercenaryRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 雇佣兵训练响应
type TrainingMercenaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	MercenaryData *MercenaryData         `protobuf:"bytes,2,opt,name=mercenary_data,json=mercenaryData,proto3" json:"mercenary_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingMercenaryResponse) Reset() {
	*x = TrainingMercenaryResponse{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingMercenaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingMercenaryResponse) ProtoMessage() {}

func (x *TrainingMercenaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingMercenaryResponse.ProtoReflect.Descriptor instead.
func (*TrainingMercenaryResponse) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{5}
}

func (x *TrainingMercenaryResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *TrainingMercenaryResponse) GetMercenaryData() *MercenaryData {
	if x != nil {
		return x.MercenaryData
	}
	return nil
}

// 升级请求
type UpgradeMercenaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MercenaryId   int64                  `protobuf:"varint,1,opt,name=mercenary_id,json=mercenaryId,proto3" json:"mercenary_id,omitempty"`
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`   // 数量
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 方式 0 消耗时间 1 立即完成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeMercenaryRequest) Reset() {
	*x = UpgradeMercenaryRequest{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeMercenaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeMercenaryRequest) ProtoMessage() {}

func (x *UpgradeMercenaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeMercenaryRequest.ProtoReflect.Descriptor instead.
func (*UpgradeMercenaryRequest) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{6}
}

func (x *UpgradeMercenaryRequest) GetMercenaryId() int64 {
	if x != nil {
		return x.MercenaryId
	}
	return 0
}

func (x *UpgradeMercenaryRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UpgradeMercenaryRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 升级响应
type UpgradeMercenaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	MercenaryData *MercenaryData         `protobuf:"bytes,2,opt,name=mercenary_data,json=mercenaryData,proto3" json:"mercenary_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeMercenaryResponse) Reset() {
	*x = UpgradeMercenaryResponse{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeMercenaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeMercenaryResponse) ProtoMessage() {}

func (x *UpgradeMercenaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeMercenaryResponse.ProtoReflect.Descriptor instead.
func (*UpgradeMercenaryResponse) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{7}
}

func (x *UpgradeMercenaryResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *UpgradeMercenaryResponse) GetMercenaryData() *MercenaryData {
	if x != nil {
		return x.MercenaryData
	}
	return nil
}

// 删除请求 测试用
type DestroyMercenaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MercenaryId   int64                  `protobuf:"varint,1,opt,name=mercenary_id,json=mercenaryId,proto3" json:"mercenary_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyMercenaryRequest) Reset() {
	*x = DestroyMercenaryRequest{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyMercenaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyMercenaryRequest) ProtoMessage() {}

func (x *DestroyMercenaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyMercenaryRequest.ProtoReflect.Descriptor instead.
func (*DestroyMercenaryRequest) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{8}
}

func (x *DestroyMercenaryRequest) GetMercenaryId() int64 {
	if x != nil {
		return x.MercenaryId
	}
	return 0
}

// 删除响应
type DestroyMercenaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyMercenaryResponse) Reset() {
	*x = DestroyMercenaryResponse{}
	mi := &file_gamesvr_mercenary_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyMercenaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyMercenaryResponse) ProtoMessage() {}

func (x *DestroyMercenaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_mercenary_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyMercenaryResponse.ProtoReflect.Descriptor instead.
func (*DestroyMercenaryResponse) Descriptor() ([]byte, []int) {
	return file_gamesvr_mercenary_proto_rawDescGZIP(), []int{9}
}

func (x *DestroyMercenaryResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

var File_gamesvr_mercenary_proto protoreflect.FileDescriptor

const file_gamesvr_mercenary_proto_rawDesc = "" +
	"\n" +
	"\x17gamesvr/mercenary.proto\x12\agamesvr\x1a\x18common/types/types.proto\"\x8e\x01\n" +
	"\x11MercenaryTimeWork\x12\x1b\n" +
	"\twork_type\x182 \x01(\x05R\bworkType\x12&\n" +
	"\x0fwork_begin_time\x183 \x01(\x03R\rworkBeginTime\x12\"\n" +
	"\rwork_end_time\x184 \x01(\x03R\vworkEndTime\x12\x10\n" +
	"\x03num\x185 \x01(\x05R\x03num\"\xc3\x01\n" +
	"\rMercenaryData\x12!\n" +
	"\fmercenary_id\x18\x01 \x01(\x03R\vmercenaryId\x12.\n" +
	"\x13mercenary_config_id\x18\x02 \x01(\x05R\x11mercenaryConfigId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x05R\x03num\x127\n" +
	"\ttime_work\x18\x05 \x01(\v2\x1a.gamesvr.MercenaryTimeWorkR\btimeWork\"\x17\n" +
	"\x15GetMyMercenaryRequest\"u\n" +
	"\x16GetMyMercenaryResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x124\n" +
	"\tmercenary\x18\x02 \x03(\v2\x16.gamesvr.MercenaryDataR\tmercenary\"p\n" +
	"\x18TrainingMercenaryRequest\x12.\n" +
	"\x13mercenary_config_id\x18\x01 \x01(\x05R\x11mercenaryConfigId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\"\x81\x01\n" +
	"\x19TrainingMercenaryResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12=\n" +
	"\x0emercenary_data\x18\x02 \x01(\v2\x16.gamesvr.MercenaryDataR\rmercenaryData\"b\n" +
	"\x17UpgradeMercenaryRequest\x12!\n" +
	"\fmercenary_id\x18\x01 \x01(\x03R\vmercenaryId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\"\x80\x01\n" +
	"\x18UpgradeMercenaryResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12=\n" +
	"\x0emercenary_data\x18\x02 \x01(\v2\x16.gamesvr.MercenaryDataR\rmercenaryData\"<\n" +
	"\x17DestroyMercenaryRequest\x12!\n" +
	"\fmercenary_id\x18\x01 \x01(\x03R\vmercenaryId\"A\n" +
	"\x18DestroyMercenaryResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04respBNZ7pitaya-game/protos/protobuf/pb/golang/gamesvr;gamesvrpb\xaa\x02\x12PitayaGame.GameSvrb\x06proto3"

var (
	file_gamesvr_mercenary_proto_rawDescOnce sync.Once
	file_gamesvr_mercenary_proto_rawDescData []byte
)

func file_gamesvr_mercenary_proto_rawDescGZIP() []byte {
	file_gamesvr_mercenary_proto_rawDescOnce.Do(func() {
		file_gamesvr_mercenary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamesvr_mercenary_proto_rawDesc), len(file_gamesvr_mercenary_proto_rawDesc)))
	})
	return file_gamesvr_mercenary_proto_rawDescData
}

var file_gamesvr_mercenary_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gamesvr_mercenary_proto_goTypes = []any{
	(*MercenaryTimeWork)(nil),         // 0: gamesvr.MercenaryTimeWork
	(*MercenaryData)(nil),             // 1: gamesvr.MercenaryData
	(*GetMyMercenaryRequest)(nil),     // 2: gamesvr.GetMyMercenaryRequest
	(*GetMyMercenaryResponse)(nil),    // 3: gamesvr.GetMyMercenaryResponse
	(*TrainingMercenaryRequest)(nil),  // 4: gamesvr.TrainingMercenaryRequest
	(*TrainingMercenaryResponse)(nil), // 5: gamesvr.TrainingMercenaryResponse
	(*UpgradeMercenaryRequest)(nil),   // 6: gamesvr.UpgradeMercenaryRequest
	(*UpgradeMercenaryResponse)(nil),  // 7: gamesvr.UpgradeMercenaryResponse
	(*DestroyMercenaryRequest)(nil),   // 8: gamesvr.DestroyMercenaryRequest
	(*DestroyMercenaryResponse)(nil),  // 9: gamesvr.DestroyMercenaryResponse
	(*types.CommonResp)(nil),          // 10: types.CommonResp
}
var file_gamesvr_mercenary_proto_depIdxs = []int32{
	0,  // 0: gamesvr.MercenaryData.time_work:type_name -> gamesvr.MercenaryTimeWork
	10, // 1: gamesvr.GetMyMercenaryResponse.resp:type_name -> types.CommonResp
	1,  // 2: gamesvr.GetMyMercenaryResponse.mercenary:type_name -> gamesvr.MercenaryData
	10, // 3: gamesvr.TrainingMercenaryResponse.resp:type_name -> types.CommonResp
	1,  // 4: gamesvr.TrainingMercenaryResponse.mercenary_data:type_name -> gamesvr.MercenaryData
	10, // 5: gamesvr.UpgradeMercenaryResponse.resp:type_name -> types.CommonResp
	1,  // 6: gamesvr.UpgradeMercenaryResponse.mercenary_data:type_name -> gamesvr.MercenaryData
	10, // 7: gamesvr.DestroyMercenaryResponse.resp:type_name -> types.CommonResp
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_gamesvr_mercenary_proto_init() }
func file_gamesvr_mercenary_proto_init() {
	if File_gamesvr_mercenary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamesvr_mercenary_proto_rawDesc), len(file_gamesvr_mercenary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamesvr_mercenary_proto_goTypes,
		DependencyIndexes: file_gamesvr_mercenary_proto_depIdxs,
		MessageInfos:      file_gamesvr_mercenary_proto_msgTypes,
	}.Build()
	File_gamesvr_mercenary_proto = out.File
	file_gamesvr_mercenary_proto_goTypes = nil
	file_gamesvr_mercenary_proto_depIdxs = nil
}
