// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: gamesvr/spell.proto

package gamesvrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 法术数据
type SpellData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpellId       int64                  `protobuf:"varint,1,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`                     // 法术ID
	SpellName     string                 `protobuf:"bytes,2,opt,name=spell_name,json=spellName,proto3" json:"spell_name,omitempty"`                // 法术名称
	SpellConfigId int32                  `protobuf:"varint,3,opt,name=spell_config_id,json=spellConfigId,proto3" json:"spell_config_id,omitempty"` // 法术ID（配置表）
	SpellType     string                 `protobuf:"bytes,4,opt,name=spell_type,json=spellType,proto3" json:"spell_type,omitempty"`                // 法术类型（RandomSpell/FullScreenSpell/TargetSpell）
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`                                        // 等级
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                             // 描述
	Cooldown      int32                  `protobuf:"varint,7,opt,name=cooldown,proto3" json:"cooldown,omitempty"`                                  // 冷却时间（秒）
	Effect        string                 `protobuf:"bytes,8,opt,name=effect,proto3" json:"effect,omitempty"`                                       // 效果描述（JSON格式）
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`               // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`              // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpellData) Reset() {
	*x = SpellData{}
	mi := &file_gamesvr_spell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellData) ProtoMessage() {}

func (x *SpellData) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_spell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellData.ProtoReflect.Descriptor instead.
func (*SpellData) Descriptor() ([]byte, []int) {
	return file_gamesvr_spell_proto_rawDescGZIP(), []int{0}
}

func (x *SpellData) GetSpellId() int64 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

func (x *SpellData) GetSpellName() string {
	if x != nil {
		return x.SpellName
	}
	return ""
}

func (x *SpellData) GetSpellConfigId() int32 {
	if x != nil {
		return x.SpellConfigId
	}
	return 0
}

func (x *SpellData) GetSpellType() string {
	if x != nil {
		return x.SpellType
	}
	return ""
}

func (x *SpellData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SpellData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SpellData) GetCooldown() int32 {
	if x != nil {
		return x.Cooldown
	}
	return 0
}

func (x *SpellData) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *SpellData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SpellData) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 获取法术信息请求
type GetSpellInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpellId       int64                  `protobuf:"varint,1,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpellInfoRequest) Reset() {
	*x = GetSpellInfoRequest{}
	mi := &file_gamesvr_spell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpellInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpellInfoRequest) ProtoMessage() {}

func (x *GetSpellInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_spell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpellInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSpellInfoRequest) Descriptor() ([]byte, []int) {
	return file_gamesvr_spell_proto_rawDescGZIP(), []int{1}
}

func (x *GetSpellInfoRequest) GetSpellId() int64 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

// 获取法术信息响应
type GetSpellInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	SpellData     *SpellData             `protobuf:"bytes,2,opt,name=spell_data,json=spellData,proto3" json:"spell_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpellInfoResponse) Reset() {
	*x = GetSpellInfoResponse{}
	mi := &file_gamesvr_spell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpellInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpellInfoResponse) ProtoMessage() {}

func (x *GetSpellInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_spell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpellInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSpellInfoResponse) Descriptor() ([]byte, []int) {
	return file_gamesvr_spell_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpellInfoResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetSpellInfoResponse) GetSpellData() *SpellData {
	if x != nil {
		return x.SpellData
	}
	return nil
}

// 获取我的已解锁法术请求
type GetMySpellsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySpellsRequest) Reset() {
	*x = GetMySpellsRequest{}
	mi := &file_gamesvr_spell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySpellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySpellsRequest) ProtoMessage() {}

func (x *GetMySpellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_spell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySpellsRequest.ProtoReflect.Descriptor instead.
func (*GetMySpellsRequest) Descriptor() ([]byte, []int) {
	return file_gamesvr_spell_proto_rawDescGZIP(), []int{3}
}

// 获取我的已解锁法术响应
type GetMySpellsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Spells        []*SpellData           `protobuf:"bytes,2,rep,name=spells,proto3" json:"spells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySpellsResponse) Reset() {
	*x = GetMySpellsResponse{}
	mi := &file_gamesvr_spell_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySpellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySpellsResponse) ProtoMessage() {}

func (x *GetMySpellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_spell_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySpellsResponse.ProtoReflect.Descriptor instead.
func (*GetMySpellsResponse) Descriptor() ([]byte, []int) {
	return file_gamesvr_spell_proto_rawDescGZIP(), []int{4}
}

func (x *GetMySpellsResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetMySpellsResponse) GetSpells() []*SpellData {
	if x != nil {
		return x.Spells
	}
	return nil
}

// 解锁法术请求
type UnlockSpellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpellConfigId int32                  `protobuf:"varint,1,opt,name=spell_config_id,json=spellConfigId,proto3" json:"spell_config_id,omitempty"` // 法术ID，user_id 从 Session 获取
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockSpellRequest) Reset() {
	*x = UnlockSpellRequest{}
	mi := &file_gamesvr_spell_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockSpellRequest) ProtoMessage() {}

func (x *UnlockSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_spell_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockSpellRequest.ProtoReflect.Descriptor instead.
func (*UnlockSpellRequest) Descriptor() ([]byte, []int) {
	return file_gamesvr_spell_proto_rawDescGZIP(), []int{5}
}

func (x *UnlockSpellRequest) GetSpellConfigId() int32 {
	if x != nil {
		return x.SpellConfigId
	}
	return 0
}

// 解锁法术响应
type UnlockSpellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	SpellId       int64                  `protobuf:"varint,2,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"` // 新解锁的法术ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockSpellResponse) Reset() {
	*x = UnlockSpellResponse{}
	mi := &file_gamesvr_spell_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockSpellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockSpellResponse) ProtoMessage() {}

func (x *UnlockSpellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_spell_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockSpellResponse.ProtoReflect.Descriptor instead.
func (*UnlockSpellResponse) Descriptor() ([]byte, []int) {
	return file_gamesvr_spell_proto_rawDescGZIP(), []int{6}
}

func (x *UnlockSpellResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *UnlockSpellResponse) GetSpellId() int64 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

// 升级法术请求
type UpgradeSpellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpellId       int64                  `protobuf:"varint,1,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeSpellRequest) Reset() {
	*x = UpgradeSpellRequest{}
	mi := &file_gamesvr_spell_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeSpellRequest) ProtoMessage() {}

func (x *UpgradeSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_spell_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeSpellRequest.ProtoReflect.Descriptor instead.
func (*UpgradeSpellRequest) Descriptor() ([]byte, []int) {
	return file_gamesvr_spell_proto_rawDescGZIP(), []int{7}
}

func (x *UpgradeSpellRequest) GetSpellId() int64 {
	if x != nil {
		return x.SpellId
	}
	return 0
}

// 升级法术响应
type UpgradeSpellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	NewLevel      int32                  `protobuf:"varint,2,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeSpellResponse) Reset() {
	*x = UpgradeSpellResponse{}
	mi := &file_gamesvr_spell_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeSpellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeSpellResponse) ProtoMessage() {}

func (x *UpgradeSpellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_spell_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeSpellResponse.ProtoReflect.Descriptor instead.
func (*UpgradeSpellResponse) Descriptor() ([]byte, []int) {
	return file_gamesvr_spell_proto_rawDescGZIP(), []int{8}
}

func (x *UpgradeSpellResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *UpgradeSpellResponse) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

var File_gamesvr_spell_proto protoreflect.FileDescriptor

const file_gamesvr_spell_proto_rawDesc = "" +
	"\n" +
	"\x13gamesvr/spell.proto\x12\agamesvr\x1a\x18common/types/types.proto\"\xb6\x02\n" +
	"\tSpellData\x12\x19\n" +
	"\bspell_id\x18\x01 \x01(\x03R\aspellId\x12\x1d\n" +
	"\n" +
	"spell_name\x18\x02 \x01(\tR\tspellName\x12&\n" +
	"\x0fspell_config_id\x18\x03 \x01(\x05R\rspellConfigId\x12\x1d\n" +
	"\n" +
	"spell_type\x18\x04 \x01(\tR\tspellType\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcooldown\x18\a \x01(\x05R\bcooldown\x12\x16\n" +
	"\x06effect\x18\b \x01(\tR\x06effect\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"0\n" +
	"\x13GetSpellInfoRequest\x12\x19\n" +
	"\bspell_id\x18\x01 \x01(\x03R\aspellId\"p\n" +
	"\x14GetSpellInfoResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x121\n" +
	"\n" +
	"spell_data\x18\x02 \x01(\v2\x12.gamesvr.SpellDataR\tspellData\"\x14\n" +
	"\x12GetMySpellsRequest\"h\n" +
	"\x13GetMySpellsResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12*\n" +
	"\x06spells\x18\x02 \x03(\v2\x12.gamesvr.SpellDataR\x06spells\"<\n" +
	"\x12UnlockSpellRequest\x12&\n" +
	"\x0fspell_config_id\x18\x01 \x01(\x05R\rspellConfigId\"W\n" +
	"\x13UnlockSpellResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12\x19\n" +
	"\bspell_id\x18\x02 \x01(\x03R\aspellId\"0\n" +
	"\x13UpgradeSpellRequest\x12\x19\n" +
	"\bspell_id\x18\x01 \x01(\x03R\aspellId\"Z\n" +
	"\x14UpgradeSpellResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12\x1b\n" +
	"\tnew_level\x18\x02 \x01(\x05R\bnewLevelBNZ7pitaya-game/protos/protobuf/pb/golang/gamesvr;gamesvrpb\xaa\x02\x12PitayaGame.GameSvrb\x06proto3"

var (
	file_gamesvr_spell_proto_rawDescOnce sync.Once
	file_gamesvr_spell_proto_rawDescData []byte
)

func file_gamesvr_spell_proto_rawDescGZIP() []byte {
	file_gamesvr_spell_proto_rawDescOnce.Do(func() {
		file_gamesvr_spell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamesvr_spell_proto_rawDesc), len(file_gamesvr_spell_proto_rawDesc)))
	})
	return file_gamesvr_spell_proto_rawDescData
}

var file_gamesvr_spell_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gamesvr_spell_proto_goTypes = []any{
	(*SpellData)(nil),            // 0: gamesvr.SpellData
	(*GetSpellInfoRequest)(nil),  // 1: gamesvr.GetSpellInfoRequest
	(*GetSpellInfoResponse)(nil), // 2: gamesvr.GetSpellInfoResponse
	(*GetMySpellsRequest)(nil),   // 3: gamesvr.GetMySpellsRequest
	(*GetMySpellsResponse)(nil),  // 4: gamesvr.GetMySpellsResponse
	(*UnlockSpellRequest)(nil),   // 5: gamesvr.UnlockSpellRequest
	(*UnlockSpellResponse)(nil),  // 6: gamesvr.UnlockSpellResponse
	(*UpgradeSpellRequest)(nil),  // 7: gamesvr.UpgradeSpellRequest
	(*UpgradeSpellResponse)(nil), // 8: gamesvr.UpgradeSpellResponse
	(*types.CommonResp)(nil),     // 9: types.CommonResp
}
var file_gamesvr_spell_proto_depIdxs = []int32{
	9, // 0: gamesvr.GetSpellInfoResponse.resp:type_name -> types.CommonResp
	0, // 1: gamesvr.GetSpellInfoResponse.spell_data:type_name -> gamesvr.SpellData
	9, // 2: gamesvr.GetMySpellsResponse.resp:type_name -> types.CommonResp
	0, // 3: gamesvr.GetMySpellsResponse.spells:type_name -> gamesvr.SpellData
	9, // 4: gamesvr.UnlockSpellResponse.resp:type_name -> types.CommonResp
	9, // 5: gamesvr.UpgradeSpellResponse.resp:type_name -> types.CommonResp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gamesvr_spell_proto_init() }
func file_gamesvr_spell_proto_init() {
	if File_gamesvr_spell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamesvr_spell_proto_rawDesc), len(file_gamesvr_spell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamesvr_spell_proto_goTypes,
		DependencyIndexes: file_gamesvr_spell_proto_depIdxs,
		MessageInfos:      file_gamesvr_spell_proto_msgTypes,
	}.Build()
	File_gamesvr_spell_proto = out.File
	file_gamesvr_spell_proto_goTypes = nil
	file_gamesvr_spell_proto_depIdxs = nil
}
