// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: gamesvr/user.proto

package gamesvrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "pitaya-game/protos/protobuf/pb/golang/common/enums"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户基础信息
type UserBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	CreateTime    int64                  `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间戳（秒）
	Coin          int64                  `protobuf:"varint,6,opt,name=coin,proto3" json:"coin,omitempty"`                               // 金币
	Diamond       int64                  `protobuf:"varint,7,opt,name=diamond,proto3" json:"diamond,omitempty"`                         // 钻石
	Wood          int64                  `protobuf:"varint,8,opt,name=wood,proto3" json:"wood,omitempty"`                               // 木材
	Stone         int64                  `protobuf:"varint,9,opt,name=stone,proto3" json:"stone,omitempty"`                             // 石头
	Meat          int64                  `protobuf:"varint,10,opt,name=meat,proto3" json:"meat,omitempty"`                              // 肉
	VipLevel      int32                  `protobuf:"varint,11,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`      // VIP等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBasicInfo) Reset() {
	*x = UserBasicInfo{}
	mi := &file_gamesvr_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasicInfo) ProtoMessage() {}

func (x *UserBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasicInfo.ProtoReflect.Descriptor instead.
func (*UserBasicInfo) Descriptor() ([]byte, []int) {
	return file_gamesvr_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserBasicInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBasicInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserBasicInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserBasicInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *UserBasicInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserBasicInfo) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *UserBasicInfo) GetDiamond() int64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

func (x *UserBasicInfo) GetWood() int64 {
	if x != nil {
		return x.Wood
	}
	return 0
}

func (x *UserBasicInfo) GetStone() int64 {
	if x != nil {
		return x.Stone
	}
	return 0
}

func (x *UserBasicInfo) GetMeat() int64 {
	if x != nil {
		return x.Meat
	}
	return 0
}

func (x *UserBasicInfo) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

// 获取用户信息请求
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_gamesvr_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_gamesvr_user_proto_rawDescGZIP(), []int{1}
}

// 获取用户信息响应
type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	UserInfo      *UserBasicInfo         `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_gamesvr_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamesvr_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_gamesvr_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetUserInfoResponse) GetUserInfo() *UserBasicInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_gamesvr_user_proto protoreflect.FileDescriptor

const file_gamesvr_user_proto_rawDesc = "" +
	"\n" +
	"\x12gamesvr/user.proto\x12\agamesvr\x1a\x18common/types/types.proto\x1a\x18common/enums/enums.proto\"\x96\x02\n" +
	"\rUserBasicInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\x03R\n" +
	"createTime\x12\x12\n" +
	"\x04coin\x18\x06 \x01(\x03R\x04coin\x12\x18\n" +
	"\adiamond\x18\a \x01(\x03R\adiamond\x12\x12\n" +
	"\x04wood\x18\b \x01(\x03R\x04wood\x12\x14\n" +
	"\x05stone\x18\t \x01(\x03R\x05stone\x12\x12\n" +
	"\x04meat\x18\n" +
	" \x01(\x03R\x04meat\x12\x1b\n" +
	"\tvip_level\x18\v \x01(\x05R\bvipLevel\"\x14\n" +
	"\x12GetUserInfoRequest\"q\n" +
	"\x13GetUserInfoResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x123\n" +
	"\tuser_info\x18\x02 \x01(\v2\x16.gamesvr.UserBasicInfoR\buserInfoBNZ7pitaya-game/protos/protobuf/pb/golang/gamesvr;gamesvrpb\xaa\x02\x12PitayaGame.GameSvrb\x06proto3"

var (
	file_gamesvr_user_proto_rawDescOnce sync.Once
	file_gamesvr_user_proto_rawDescData []byte
)

func file_gamesvr_user_proto_rawDescGZIP() []byte {
	file_gamesvr_user_proto_rawDescOnce.Do(func() {
		file_gamesvr_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamesvr_user_proto_rawDesc), len(file_gamesvr_user_proto_rawDesc)))
	})
	return file_gamesvr_user_proto_rawDescData
}

var file_gamesvr_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gamesvr_user_proto_goTypes = []any{
	(*UserBasicInfo)(nil),       // 0: gamesvr.UserBasicInfo
	(*GetUserInfoRequest)(nil),  // 1: gamesvr.GetUserInfoRequest
	(*GetUserInfoResponse)(nil), // 2: gamesvr.GetUserInfoResponse
	(*types.CommonResp)(nil),    // 3: types.CommonResp
}
var file_gamesvr_user_proto_depIdxs = []int32{
	3, // 0: gamesvr.GetUserInfoResponse.resp:type_name -> types.CommonResp
	0, // 1: gamesvr.GetUserInfoResponse.user_info:type_name -> gamesvr.UserBasicInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gamesvr_user_proto_init() }
func file_gamesvr_user_proto_init() {
	if File_gamesvr_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamesvr_user_proto_rawDesc), len(file_gamesvr_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamesvr_user_proto_goTypes,
		DependencyIndexes: file_gamesvr_user_proto_depIdxs,
		MessageInfos:      file_gamesvr_user_proto_msgTypes,
	}.Build()
	File_gamesvr_user_proto = out.File
	file_gamesvr_user_proto_goTypes = nil
	file_gamesvr_user_proto_depIdxs = nil
}
