// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: battlesvr/battle.proto

package battlesvrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发起进攻请求
type StartAttackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       int64                  `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // 匹配ID（从 MatchmakingSvr 获取）
	ArmyId        int64                  `protobuf:"varint,2,opt,name=army_id,json=armyId,proto3" json:"army_id,omitempty"`    // 进攻方使用的军队编组ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAttackRequest) Reset() {
	*x = StartAttackRequest{}
	mi := &file_battlesvr_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAttackRequest) ProtoMessage() {}

func (x *StartAttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAttackRequest.ProtoReflect.Descriptor instead.
func (*StartAttackRequest) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{0}
}

func (x *StartAttackRequest) GetMatchId() int64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *StartAttackRequest) GetArmyId() int64 {
	if x != nil {
		return x.ArmyId
	}
	return 0
}

// 发起进攻响应
type StartAttackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	BattleId      int64                  `protobuf:"varint,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // 战斗ID
	InitData      *BattleInitData        `protobuf:"bytes,3,opt,name=init_data,json=initData,proto3" json:"init_data,omitempty"`  // 战斗初始化数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAttackResponse) Reset() {
	*x = StartAttackResponse{}
	mi := &file_battlesvr_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAttackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAttackResponse) ProtoMessage() {}

func (x *StartAttackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAttackResponse.ProtoReflect.Descriptor instead.
func (*StartAttackResponse) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{1}
}

func (x *StartAttackResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *StartAttackResponse) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *StartAttackResponse) GetInitData() *BattleInitData {
	if x != nil {
		return x.InitData
	}
	return nil
}

// 战斗初始化数据（客户端用于初始化战场）
type BattleInitData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 防御方基地信息
	DefenderBase *DefenderBaseData `protobuf:"bytes,1,opt,name=defender_base,json=defenderBase,proto3" json:"defender_base,omitempty"`
	// 进攻方军队信息
	AttackerArmy *AttackerArmyData `protobuf:"bytes,2,opt,name=attacker_army,json=attackerArmy,proto3" json:"attacker_army,omitempty"`
	// 战斗环境配置
	BattleDuration  int32 `protobuf:"varint,3,opt,name=battle_duration,json=battleDuration,proto3" json:"battle_duration,omitempty"`      // 战斗时长（秒）
	BattleStartTime int64 `protobuf:"varint,4,opt,name=battle_start_time,json=battleStartTime,proto3" json:"battle_start_time,omitempty"` // 战斗开始时间（Unix秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BattleInitData) Reset() {
	*x = BattleInitData{}
	mi := &file_battlesvr_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleInitData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleInitData) ProtoMessage() {}

func (x *BattleInitData) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleInitData.ProtoReflect.Descriptor instead.
func (*BattleInitData) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{2}
}

func (x *BattleInitData) GetDefenderBase() *DefenderBaseData {
	if x != nil {
		return x.DefenderBase
	}
	return nil
}

func (x *BattleInitData) GetAttackerArmy() *AttackerArmyData {
	if x != nil {
		return x.AttackerArmy
	}
	return nil
}

func (x *BattleInitData) GetBattleDuration() int32 {
	if x != nil {
		return x.BattleDuration
	}
	return 0
}

func (x *BattleInitData) GetBattleStartTime() int64 {
	if x != nil {
		return x.BattleStartTime
	}
	return 0
}

// 防御方基地数据
type DefenderBaseData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DefenderId       string                 `protobuf:"bytes,1,opt,name=defender_id,json=defenderId,proto3" json:"defender_id,omitempty"`                   // 防御者ID
	DefenderUsername string                 `protobuf:"bytes,2,opt,name=defender_username,json=defenderUsername,proto3" json:"defender_username,omitempty"` // 防御者用户名
	DefenderTrophy   int64                  `protobuf:"varint,3,opt,name=defender_trophy,json=defenderTrophy,proto3" json:"defender_trophy,omitempty"`      // 防御者奖杯数
	TownHallLevel    int32                  `protobuf:"varint,4,opt,name=town_hall_level,json=townHallLevel,proto3" json:"town_hall_level,omitempty"`       // 大本营等级
	LayoutData       []byte                 `protobuf:"bytes,5,opt,name=layout_data,json=layoutData,proto3" json:"layout_data,omitempty"`                   // 基地布局数据（JSON或压缩格式）
	// 可掠夺的资源
	AvailableGold       int64 `protobuf:"varint,6,opt,name=available_gold,json=availableGold,proto3" json:"available_gold,omitempty"`                     // 可掠夺金币
	AvailableElixir     int64 `protobuf:"varint,7,opt,name=available_elixir,json=availableElixir,proto3" json:"available_elixir,omitempty"`               // 可掠夺圣水
	AvailableDarkElixir int64 `protobuf:"varint,8,opt,name=available_dark_elixir,json=availableDarkElixir,proto3" json:"available_dark_elixir,omitempty"` // 可掠夺黑油
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DefenderBaseData) Reset() {
	*x = DefenderBaseData{}
	mi := &file_battlesvr_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefenderBaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefenderBaseData) ProtoMessage() {}

func (x *DefenderBaseData) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefenderBaseData.ProtoReflect.Descriptor instead.
func (*DefenderBaseData) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{3}
}

func (x *DefenderBaseData) GetDefenderId() string {
	if x != nil {
		return x.DefenderId
	}
	return ""
}

func (x *DefenderBaseData) GetDefenderUsername() string {
	if x != nil {
		return x.DefenderUsername
	}
	return ""
}

func (x *DefenderBaseData) GetDefenderTrophy() int64 {
	if x != nil {
		return x.DefenderTrophy
	}
	return 0
}

func (x *DefenderBaseData) GetTownHallLevel() int32 {
	if x != nil {
		return x.TownHallLevel
	}
	return 0
}

func (x *DefenderBaseData) GetLayoutData() []byte {
	if x != nil {
		return x.LayoutData
	}
	return nil
}

func (x *DefenderBaseData) GetAvailableGold() int64 {
	if x != nil {
		return x.AvailableGold
	}
	return 0
}

func (x *DefenderBaseData) GetAvailableElixir() int64 {
	if x != nil {
		return x.AvailableElixir
	}
	return 0
}

func (x *DefenderBaseData) GetAvailableDarkElixir() int64 {
	if x != nil {
		return x.AvailableDarkElixir
	}
	return 0
}

// 进攻方军队数据
type AttackerArmyData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AttackerId       string                 `protobuf:"bytes,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`                   // 进攻者ID
	AttackerUsername string                 `protobuf:"bytes,2,opt,name=attacker_username,json=attackerUsername,proto3" json:"attacker_username,omitempty"` // 进攻者用户名
	AttackerTrophy   int64                  `protobuf:"varint,3,opt,name=attacker_trophy,json=attackerTrophy,proto3" json:"attacker_trophy,omitempty"`      // 进攻者奖杯数
	ArmyId           int64                  `protobuf:"varint,4,opt,name=army_id,json=armyId,proto3" json:"army_id,omitempty"`                              // 军队编组ID
	ArmyName         string                 `protobuf:"bytes,5,opt,name=army_name,json=armyName,proto3" json:"army_name,omitempty"`                         // 军队编组名称
	ArmyData         []byte                 `protobuf:"bytes,6,opt,name=army_data,json=armyData,proto3" json:"army_data,omitempty"`                         // 军队详细数据（包含英雄、佣兵、法术，JSON或压缩格式）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttackerArmyData) Reset() {
	*x = AttackerArmyData{}
	mi := &file_battlesvr_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackerArmyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackerArmyData) ProtoMessage() {}

func (x *AttackerArmyData) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackerArmyData.ProtoReflect.Descriptor instead.
func (*AttackerArmyData) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{4}
}

func (x *AttackerArmyData) GetAttackerId() string {
	if x != nil {
		return x.AttackerId
	}
	return ""
}

func (x *AttackerArmyData) GetAttackerUsername() string {
	if x != nil {
		return x.AttackerUsername
	}
	return ""
}

func (x *AttackerArmyData) GetAttackerTrophy() int64 {
	if x != nil {
		return x.AttackerTrophy
	}
	return 0
}

func (x *AttackerArmyData) GetArmyId() int64 {
	if x != nil {
		return x.ArmyId
	}
	return 0
}

func (x *AttackerArmyData) GetArmyName() string {
	if x != nil {
		return x.ArmyName
	}
	return ""
}

func (x *AttackerArmyData) GetArmyData() []byte {
	if x != nil {
		return x.ArmyData
	}
	return nil
}

// 记录战斗动作请求（客户端定时批量上报）
type RecordBattleActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Actions       []*BattleAction        `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"` // 动作列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordBattleActionsRequest) Reset() {
	*x = RecordBattleActionsRequest{}
	mi := &file_battlesvr_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordBattleActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBattleActionsRequest) ProtoMessage() {}

func (x *RecordBattleActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBattleActionsRequest.ProtoReflect.Descriptor instead.
func (*RecordBattleActionsRequest) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{5}
}

func (x *RecordBattleActionsRequest) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *RecordBattleActionsRequest) GetActions() []*BattleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

// 记录战斗动作响应
type RecordBattleActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	RecordedCount int32                  `protobuf:"varint,2,opt,name=recorded_count,json=recordedCount,proto3" json:"recorded_count,omitempty"` // 成功记录的动作数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordBattleActionsResponse) Reset() {
	*x = RecordBattleActionsResponse{}
	mi := &file_battlesvr_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordBattleActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBattleActionsResponse) ProtoMessage() {}

func (x *RecordBattleActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBattleActionsResponse.ProtoReflect.Descriptor instead.
func (*RecordBattleActionsResponse) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{6}
}

func (x *RecordBattleActionsResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *RecordBattleActionsResponse) GetRecordedCount() int32 {
	if x != nil {
		return x.RecordedCount
	}
	return 0
}

// 战斗动作（部署单位、使用法术）
type BattleAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    int32                  `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`    // 动作类型：1=部署英雄，2=部署佣兵，3=使用法术
	UnitId        int32                  `protobuf:"varint,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`                // 单位ID（英雄ID、佣兵配置ID、法术配置ID）
	Position      *types.Vector2         `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`                           // 部署位置
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // 动作时间戳（战斗开始后的毫秒数）
	ExtraData     string                 `protobuf:"bytes,5,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`        // 扩展数据（JSON格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleAction) Reset() {
	*x = BattleAction{}
	mi := &file_battlesvr_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleAction) ProtoMessage() {}

func (x *BattleAction) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleAction.ProtoReflect.Descriptor instead.
func (*BattleAction) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{7}
}

func (x *BattleAction) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *BattleAction) GetUnitId() int32 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *BattleAction) GetPosition() *types.Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BattleAction) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *BattleAction) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

// 提交战斗结果请求（客户端战斗结束后上报）
type SubmitBattleResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	ResultData    *BattleResultData      `protobuf:"bytes,2,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBattleResultRequest) Reset() {
	*x = SubmitBattleResultRequest{}
	mi := &file_battlesvr_battle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBattleResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBattleResultRequest) ProtoMessage() {}

func (x *SubmitBattleResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBattleResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitBattleResultRequest) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitBattleResultRequest) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *SubmitBattleResultRequest) GetResultData() *BattleResultData {
	if x != nil {
		return x.ResultData
	}
	return nil
}

// 提交战斗结果响应
type SubmitBattleResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Rewards       *BattleRewards         `protobuf:"bytes,2,opt,name=rewards,proto3" json:"rewards,omitempty"`                               // 战斗奖励
	TrophyChange  *TrophyChange          `protobuf:"bytes,3,opt,name=trophy_change,json=trophyChange,proto3" json:"trophy_change,omitempty"` // 奖杯变化
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBattleResultResponse) Reset() {
	*x = SubmitBattleResultResponse{}
	mi := &file_battlesvr_battle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBattleResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBattleResultResponse) ProtoMessage() {}

func (x *SubmitBattleResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBattleResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitBattleResultResponse) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitBattleResultResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *SubmitBattleResultResponse) GetRewards() *BattleRewards {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *SubmitBattleResultResponse) GetTrophyChange() *TrophyChange {
	if x != nil {
		return x.TrophyChange
	}
	return nil
}

// 战斗结果数据（客户端计算）
type BattleResultData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DestructionPercentage int32                  `protobuf:"varint,1,opt,name=destruction_percentage,json=destructionPercentage,proto3" json:"destruction_percentage,omitempty"`   // 摧毁百分比（0-100）
	Stars                 int32                  `protobuf:"varint,2,opt,name=stars,proto3" json:"stars,omitempty"`                                                                // 获得星级（0-3）
	BattleDurationSeconds int32                  `protobuf:"varint,3,opt,name=battle_duration_seconds,json=battleDurationSeconds,proto3" json:"battle_duration_seconds,omitempty"` // 实际战斗时长（秒）
	// 摧毁统计
	DestroyedBuildings int32 `protobuf:"varint,4,opt,name=destroyed_buildings,json=destroyedBuildings,proto3" json:"destroyed_buildings,omitempty"` // 摧毁的建筑数量
	TotalBuildings     int32 `protobuf:"varint,5,opt,name=total_buildings,json=totalBuildings,proto3" json:"total_buildings,omitempty"`             // 总建筑数量
	TownHallDestroyed  bool  `protobuf:"varint,6,opt,name=town_hall_destroyed,json=townHallDestroyed,proto3" json:"town_hall_destroyed,omitempty"`  // 是否摧毁大本营
	// 资源掠夺
	LootedGold       int64 `protobuf:"varint,7,opt,name=looted_gold,json=lootedGold,proto3" json:"looted_gold,omitempty"`                     // 掠夺的金币
	LootedElixir     int64 `protobuf:"varint,8,opt,name=looted_elixir,json=lootedElixir,proto3" json:"looted_elixir,omitempty"`               // 掠夺的圣水
	LootedDarkElixir int64 `protobuf:"varint,9,opt,name=looted_dark_elixir,json=lootedDarkElixir,proto3" json:"looted_dark_elixir,omitempty"` // 掠夺的黑油
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BattleResultData) Reset() {
	*x = BattleResultData{}
	mi := &file_battlesvr_battle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResultData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResultData) ProtoMessage() {}

func (x *BattleResultData) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResultData.ProtoReflect.Descriptor instead.
func (*BattleResultData) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{10}
}

func (x *BattleResultData) GetDestructionPercentage() int32 {
	if x != nil {
		return x.DestructionPercentage
	}
	return 0
}

func (x *BattleResultData) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *BattleResultData) GetBattleDurationSeconds() int32 {
	if x != nil {
		return x.BattleDurationSeconds
	}
	return 0
}

func (x *BattleResultData) GetDestroyedBuildings() int32 {
	if x != nil {
		return x.DestroyedBuildings
	}
	return 0
}

func (x *BattleResultData) GetTotalBuildings() int32 {
	if x != nil {
		return x.TotalBuildings
	}
	return 0
}

func (x *BattleResultData) GetTownHallDestroyed() bool {
	if x != nil {
		return x.TownHallDestroyed
	}
	return false
}

func (x *BattleResultData) GetLootedGold() int64 {
	if x != nil {
		return x.LootedGold
	}
	return 0
}

func (x *BattleResultData) GetLootedElixir() int64 {
	if x != nil {
		return x.LootedElixir
	}
	return 0
}

func (x *BattleResultData) GetLootedDarkElixir() int64 {
	if x != nil {
		return x.LootedDarkElixir
	}
	return 0
}

// 战斗奖励
type BattleRewards struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 资源奖励
	Gold       int64 `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`                               // 金币
	Elixir     int64 `protobuf:"varint,2,opt,name=elixir,proto3" json:"elixir,omitempty"`                           // 圣水
	DarkElixir int64 `protobuf:"varint,3,opt,name=dark_elixir,json=darkElixir,proto3" json:"dark_elixir,omitempty"` // 黑油
	// 经验奖励
	Exp int64 `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"` // 经验值
	// 额外奖励（宝箱、道具等）
	BonusItems    []*ItemReward `protobuf:"bytes,5,rep,name=bonus_items,json=bonusItems,proto3" json:"bonus_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRewards) Reset() {
	*x = BattleRewards{}
	mi := &file_battlesvr_battle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRewards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRewards) ProtoMessage() {}

func (x *BattleRewards) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRewards.ProtoReflect.Descriptor instead.
func (*BattleRewards) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{11}
}

func (x *BattleRewards) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *BattleRewards) GetElixir() int64 {
	if x != nil {
		return x.Elixir
	}
	return 0
}

func (x *BattleRewards) GetDarkElixir() int64 {
	if x != nil {
		return x.DarkElixir
	}
	return 0
}

func (x *BattleRewards) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *BattleRewards) GetBonusItems() []*ItemReward {
	if x != nil {
		return x.BonusItems
	}
	return nil
}

// 物品奖励
type ItemReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemConfigId  int32                  `protobuf:"varint,1,opt,name=item_config_id,json=itemConfigId,proto3" json:"item_config_id,omitempty"` // 物品配置表ID
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                                     // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemReward) Reset() {
	*x = ItemReward{}
	mi := &file_battlesvr_battle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReward) ProtoMessage() {}

func (x *ItemReward) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReward.ProtoReflect.Descriptor instead.
func (*ItemReward) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{12}
}

func (x *ItemReward) GetItemConfigId() int32 {
	if x != nil {
		return x.ItemConfigId
	}
	return 0
}

func (x *ItemReward) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 奖杯变化
type TrophyChange struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttackerOldTrophy int64                  `protobuf:"varint,1,opt,name=attacker_old_trophy,json=attackerOldTrophy,proto3" json:"attacker_old_trophy,omitempty"` // 进攻方原奖杯数
	AttackerNewTrophy int64                  `protobuf:"varint,2,opt,name=attacker_new_trophy,json=attackerNewTrophy,proto3" json:"attacker_new_trophy,omitempty"` // 进攻方新奖杯数
	AttackerChange    int32                  `protobuf:"varint,3,opt,name=attacker_change,json=attackerChange,proto3" json:"attacker_change,omitempty"`            // 进攻方变化（正/负）
	DefenderOldTrophy int64                  `protobuf:"varint,4,opt,name=defender_old_trophy,json=defenderOldTrophy,proto3" json:"defender_old_trophy,omitempty"` // 防御方原奖杯数
	DefenderNewTrophy int64                  `protobuf:"varint,5,opt,name=defender_new_trophy,json=defenderNewTrophy,proto3" json:"defender_new_trophy,omitempty"` // 防御方新奖杯数
	DefenderChange    int32                  `protobuf:"varint,6,opt,name=defender_change,json=defenderChange,proto3" json:"defender_change,omitempty"`            // 防御方变化（正/负）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrophyChange) Reset() {
	*x = TrophyChange{}
	mi := &file_battlesvr_battle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrophyChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrophyChange) ProtoMessage() {}

func (x *TrophyChange) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrophyChange.ProtoReflect.Descriptor instead.
func (*TrophyChange) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{13}
}

func (x *TrophyChange) GetAttackerOldTrophy() int64 {
	if x != nil {
		return x.AttackerOldTrophy
	}
	return 0
}

func (x *TrophyChange) GetAttackerNewTrophy() int64 {
	if x != nil {
		return x.AttackerNewTrophy
	}
	return 0
}

func (x *TrophyChange) GetAttackerChange() int32 {
	if x != nil {
		return x.AttackerChange
	}
	return 0
}

func (x *TrophyChange) GetDefenderOldTrophy() int64 {
	if x != nil {
		return x.DefenderOldTrophy
	}
	return 0
}

func (x *TrophyChange) GetDefenderNewTrophy() int64 {
	if x != nil {
		return x.DefenderNewTrophy
	}
	return 0
}

func (x *TrophyChange) GetDefenderChange() int32 {
	if x != nil {
		return x.DefenderChange
	}
	return 0
}

// 获取战斗回放请求
type GetBattleReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleReplayRequest) Reset() {
	*x = GetBattleReplayRequest{}
	mi := &file_battlesvr_battle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleReplayRequest) ProtoMessage() {}

func (x *GetBattleReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleReplayRequest.ProtoReflect.Descriptor instead.
func (*GetBattleReplayRequest) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{14}
}

func (x *GetBattleReplayRequest) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

// 获取战斗回放响应
type GetBattleReplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	ReplayData    *BattleReplayData      `protobuf:"bytes,2,opt,name=replay_data,json=replayData,proto3" json:"replay_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleReplayResponse) Reset() {
	*x = GetBattleReplayResponse{}
	mi := &file_battlesvr_battle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleReplayResponse) ProtoMessage() {}

func (x *GetBattleReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleReplayResponse.ProtoReflect.Descriptor instead.
func (*GetBattleReplayResponse) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{15}
}

func (x *GetBattleReplayResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetBattleReplayResponse) GetReplayData() *BattleReplayData {
	if x != nil {
		return x.ReplayData
	}
	return nil
}

// 战斗回放数据
type BattleReplayData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	InitData      *BattleInitData        `protobuf:"bytes,2,opt,name=init_data,json=initData,proto3" json:"init_data,omitempty"`        // 战斗初始化数据
	Actions       []*BattleAction        `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`                          // 战斗动作时间轴
	ResultData    *BattleResultData      `protobuf:"bytes,4,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`  // 战斗结果
	BattleTime    int64                  `protobuf:"varint,5,opt,name=battle_time,json=battleTime,proto3" json:"battle_time,omitempty"` // 战斗发生时间（Unix秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleReplayData) Reset() {
	*x = BattleReplayData{}
	mi := &file_battlesvr_battle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleReplayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleReplayData) ProtoMessage() {}

func (x *BattleReplayData) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleReplayData.ProtoReflect.Descriptor instead.
func (*BattleReplayData) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{16}
}

func (x *BattleReplayData) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleReplayData) GetInitData() *BattleInitData {
	if x != nil {
		return x.InitData
	}
	return nil
}

func (x *BattleReplayData) GetActions() []*BattleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *BattleReplayData) GetResultData() *BattleResultData {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *BattleReplayData) GetBattleTime() int64 {
	if x != nil {
		return x.BattleTime
	}
	return 0
}

// 获取我的进攻记录请求
type GetMyAttackRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyAttackRecordsRequest) Reset() {
	*x = GetMyAttackRecordsRequest{}
	mi := &file_battlesvr_battle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyAttackRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyAttackRecordsRequest) ProtoMessage() {}

func (x *GetMyAttackRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyAttackRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetMyAttackRecordsRequest) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{17}
}

func (x *GetMyAttackRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyAttackRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取我的进攻记录响应
type GetMyAttackRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Records       []*BattleRecordBrief   `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyAttackRecordsResponse) Reset() {
	*x = GetMyAttackRecordsResponse{}
	mi := &file_battlesvr_battle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyAttackRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyAttackRecordsResponse) ProtoMessage() {}

func (x *GetMyAttackRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyAttackRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetMyAttackRecordsResponse) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{18}
}

func (x *GetMyAttackRecordsResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetMyAttackRecordsResponse) GetRecords() []*BattleRecordBrief {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetMyAttackRecordsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 获取我的防守记录请求
type GetMyDefenseRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyDefenseRecordsRequest) Reset() {
	*x = GetMyDefenseRecordsRequest{}
	mi := &file_battlesvr_battle_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyDefenseRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyDefenseRecordsRequest) ProtoMessage() {}

func (x *GetMyDefenseRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyDefenseRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetMyDefenseRecordsRequest) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{19}
}

func (x *GetMyDefenseRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyDefenseRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取我的防守记录响应
type GetMyDefenseRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Records       []*BattleRecordBrief   `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyDefenseRecordsResponse) Reset() {
	*x = GetMyDefenseRecordsResponse{}
	mi := &file_battlesvr_battle_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyDefenseRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyDefenseRecordsResponse) ProtoMessage() {}

func (x *GetMyDefenseRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyDefenseRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetMyDefenseRecordsResponse) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{20}
}

func (x *GetMyDefenseRecordsResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetMyDefenseRecordsResponse) GetRecords() []*BattleRecordBrief {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetMyDefenseRecordsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 战斗记录简要信息
type BattleRecordBrief struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BattleId         int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	OpponentId       string                 `protobuf:"bytes,2,opt,name=opponent_id,json=opponentId,proto3" json:"opponent_id,omitempty"`                   // 对手ID
	OpponentUsername string                 `protobuf:"bytes,3,opt,name=opponent_username,json=opponentUsername,proto3" json:"opponent_username,omitempty"` // 对手用户名
	OpponentTrophy   int64                  `protobuf:"varint,4,opt,name=opponent_trophy,json=opponentTrophy,proto3" json:"opponent_trophy,omitempty"`      // 对手奖杯数
	// 战斗结果
	Stars                 int32 `protobuf:"varint,5,opt,name=stars,proto3" json:"stars,omitempty"`                                                              // 星级
	DestructionPercentage int32 `protobuf:"varint,6,opt,name=destruction_percentage,json=destructionPercentage,proto3" json:"destruction_percentage,omitempty"` // 摧毁百分比
	TrophyChange          int32 `protobuf:"varint,7,opt,name=trophy_change,json=trophyChange,proto3" json:"trophy_change,omitempty"`                            // 奖杯变化（正/负）
	// 资源变化
	ResourceChangeGold   int64 `protobuf:"varint,8,opt,name=resource_change_gold,json=resourceChangeGold,proto3" json:"resource_change_gold,omitempty"`       // 金币变化
	ResourceChangeElixir int64 `protobuf:"varint,9,opt,name=resource_change_elixir,json=resourceChangeElixir,proto3" json:"resource_change_elixir,omitempty"` // 圣水变化
	BattleTime           int64 `protobuf:"varint,10,opt,name=battle_time,json=battleTime,proto3" json:"battle_time,omitempty"`                                // 战斗时间（Unix秒）
	IsAttack             bool  `protobuf:"varint,11,opt,name=is_attack,json=isAttack,proto3" json:"is_attack,omitempty"`                                      // true=进攻记录，false=防守记录
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BattleRecordBrief) Reset() {
	*x = BattleRecordBrief{}
	mi := &file_battlesvr_battle_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRecordBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRecordBrief) ProtoMessage() {}

func (x *BattleRecordBrief) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRecordBrief.ProtoReflect.Descriptor instead.
func (*BattleRecordBrief) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{21}
}

func (x *BattleRecordBrief) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleRecordBrief) GetOpponentId() string {
	if x != nil {
		return x.OpponentId
	}
	return ""
}

func (x *BattleRecordBrief) GetOpponentUsername() string {
	if x != nil {
		return x.OpponentUsername
	}
	return ""
}

func (x *BattleRecordBrief) GetOpponentTrophy() int64 {
	if x != nil {
		return x.OpponentTrophy
	}
	return 0
}

func (x *BattleRecordBrief) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *BattleRecordBrief) GetDestructionPercentage() int32 {
	if x != nil {
		return x.DestructionPercentage
	}
	return 0
}

func (x *BattleRecordBrief) GetTrophyChange() int32 {
	if x != nil {
		return x.TrophyChange
	}
	return 0
}

func (x *BattleRecordBrief) GetResourceChangeGold() int64 {
	if x != nil {
		return x.ResourceChangeGold
	}
	return 0
}

func (x *BattleRecordBrief) GetResourceChangeElixir() int64 {
	if x != nil {
		return x.ResourceChangeElixir
	}
	return 0
}

func (x *BattleRecordBrief) GetBattleTime() int64 {
	if x != nil {
		return x.BattleTime
	}
	return 0
}

func (x *BattleRecordBrief) GetIsAttack() bool {
	if x != nil {
		return x.IsAttack
	}
	return false
}

// 获取战斗详情请求（供 GameSvr 等服务调用）
type GetBattleDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleDetailRequest) Reset() {
	*x = GetBattleDetailRequest{}
	mi := &file_battlesvr_battle_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleDetailRequest) ProtoMessage() {}

func (x *GetBattleDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleDetailRequest.ProtoReflect.Descriptor instead.
func (*GetBattleDetailRequest) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{22}
}

func (x *GetBattleDetailRequest) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

// 获取战斗详情响应
type GetBattleDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	BattleDetail  *BattleDetail          `protobuf:"bytes,2,opt,name=battle_detail,json=battleDetail,proto3" json:"battle_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleDetailResponse) Reset() {
	*x = GetBattleDetailResponse{}
	mi := &file_battlesvr_battle_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleDetailResponse) ProtoMessage() {}

func (x *GetBattleDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleDetailResponse.ProtoReflect.Descriptor instead.
func (*GetBattleDetailResponse) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{23}
}

func (x *GetBattleDetailResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetBattleDetailResponse) GetBattleDetail() *BattleDetail {
	if x != nil {
		return x.BattleDetail
	}
	return nil
}

// 战斗详情（完整数据）
type BattleDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      int64                  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	AttackerId    string                 `protobuf:"bytes,2,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`       // 进攻者ID
	DefenderId    string                 `protobuf:"bytes,3,opt,name=defender_id,json=defenderId,proto3" json:"defender_id,omitempty"`       // 防御者ID
	InitData      *BattleInitData        `protobuf:"bytes,4,opt,name=init_data,json=initData,proto3" json:"init_data,omitempty"`             // 初始化数据
	Actions       []*BattleAction        `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`                               // 动作时间轴
	ResultData    *BattleResultData      `protobuf:"bytes,6,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`       // 结果数据
	Rewards       *BattleRewards         `protobuf:"bytes,7,opt,name=rewards,proto3" json:"rewards,omitempty"`                               // 奖励数据
	TrophyChange  *TrophyChange          `protobuf:"bytes,8,opt,name=trophy_change,json=trophyChange,proto3" json:"trophy_change,omitempty"` // 奖杯变化
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                                // 战斗状态：1=进行中，2=已完成，3=已放弃
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // 创建时间
	FinishedAt    int64                  `protobuf:"varint,11,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`     // 结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleDetail) Reset() {
	*x = BattleDetail{}
	mi := &file_battlesvr_battle_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleDetail) ProtoMessage() {}

func (x *BattleDetail) ProtoReflect() protoreflect.Message {
	mi := &file_battlesvr_battle_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleDetail.ProtoReflect.Descriptor instead.
func (*BattleDetail) Descriptor() ([]byte, []int) {
	return file_battlesvr_battle_proto_rawDescGZIP(), []int{24}
}

func (x *BattleDetail) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleDetail) GetAttackerId() string {
	if x != nil {
		return x.AttackerId
	}
	return ""
}

func (x *BattleDetail) GetDefenderId() string {
	if x != nil {
		return x.DefenderId
	}
	return ""
}

func (x *BattleDetail) GetInitData() *BattleInitData {
	if x != nil {
		return x.InitData
	}
	return nil
}

func (x *BattleDetail) GetActions() []*BattleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *BattleDetail) GetResultData() *BattleResultData {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *BattleDetail) GetRewards() *BattleRewards {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *BattleDetail) GetTrophyChange() *TrophyChange {
	if x != nil {
		return x.TrophyChange
	}
	return nil
}

func (x *BattleDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BattleDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BattleDetail) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

var File_battlesvr_battle_proto protoreflect.FileDescriptor

const file_battlesvr_battle_proto_rawDesc = "" +
	"\n" +
	"\x16battlesvr/battle.proto\x12\tbattlesvr\x1a\x18common/types/types.proto\"H\n" +
	"\x12StartAttackRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\x03R\amatchId\x12\x17\n" +
	"\aarmy_id\x18\x02 \x01(\x03R\x06armyId\"\x91\x01\n" +
	"\x13StartAttackResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\x03R\bbattleId\x126\n" +
	"\tinit_data\x18\x03 \x01(\v2\x19.battlesvr.BattleInitDataR\binitData\"\xe9\x01\n" +
	"\x0eBattleInitData\x12@\n" +
	"\rdefender_base\x18\x01 \x01(\v2\x1b.battlesvr.DefenderBaseDataR\fdefenderBase\x12@\n" +
	"\rattacker_army\x18\x02 \x01(\v2\x1b.battlesvr.AttackerArmyDataR\fattackerArmy\x12'\n" +
	"\x0fbattle_duration\x18\x03 \x01(\x05R\x0ebattleDuration\x12*\n" +
	"\x11battle_start_time\x18\x04 \x01(\x03R\x0fbattleStartTime\"\xd8\x02\n" +
	"\x10DefenderBaseData\x12\x1f\n" +
	"\vdefender_id\x18\x01 \x01(\tR\n" +
	"defenderId\x12+\n" +
	"\x11defender_username\x18\x02 \x01(\tR\x10defenderUsername\x12'\n" +
	"\x0fdefender_trophy\x18\x03 \x01(\x03R\x0edefenderTrophy\x12&\n" +
	"\x0ftown_hall_level\x18\x04 \x01(\x05R\rtownHallLevel\x12\x1f\n" +
	"\vlayout_data\x18\x05 \x01(\fR\n" +
	"layoutData\x12%\n" +
	"\x0eavailable_gold\x18\x06 \x01(\x03R\ravailableGold\x12)\n" +
	"\x10available_elixir\x18\a \x01(\x03R\x0favailableElixir\x122\n" +
	"\x15available_dark_elixir\x18\b \x01(\x03R\x13availableDarkElixir\"\xdc\x01\n" +
	"\x10AttackerArmyData\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\tR\n" +
	"attackerId\x12+\n" +
	"\x11attacker_username\x18\x02 \x01(\tR\x10attackerUsername\x12'\n" +
	"\x0fattacker_trophy\x18\x03 \x01(\x03R\x0eattackerTrophy\x12\x17\n" +
	"\aarmy_id\x18\x04 \x01(\x03R\x06armyId\x12\x1b\n" +
	"\tarmy_name\x18\x05 \x01(\tR\barmyName\x12\x1b\n" +
	"\tarmy_data\x18\x06 \x01(\fR\barmyData\"l\n" +
	"\x1aRecordBattleActionsRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x121\n" +
	"\aactions\x18\x02 \x03(\v2\x17.battlesvr.BattleActionR\aactions\"k\n" +
	"\x1bRecordBattleActionsResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12%\n" +
	"\x0erecorded_count\x18\x02 \x01(\x05R\rrecordedCount\"\xb6\x01\n" +
	"\fBattleAction\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\x05R\n" +
	"actionType\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\x05R\x06unitId\x12*\n" +
	"\bposition\x18\x03 \x01(\v2\x0e.types.Vector2R\bposition\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"extra_data\x18\x05 \x01(\tR\textraData\"v\n" +
	"\x19SubmitBattleResultRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12<\n" +
	"\vresult_data\x18\x02 \x01(\v2\x1b.battlesvr.BattleResultDataR\n" +
	"resultData\"\xb5\x01\n" +
	"\x1aSubmitBattleResultResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x122\n" +
	"\arewards\x18\x02 \x01(\v2\x18.battlesvr.BattleRewardsR\arewards\x12<\n" +
	"\rtrophy_change\x18\x03 \x01(\v2\x17.battlesvr.TrophyChangeR\ftrophyChange\"\x95\x03\n" +
	"\x10BattleResultData\x125\n" +
	"\x16destruction_percentage\x18\x01 \x01(\x05R\x15destructionPercentage\x12\x14\n" +
	"\x05stars\x18\x02 \x01(\x05R\x05stars\x126\n" +
	"\x17battle_duration_seconds\x18\x03 \x01(\x05R\x15battleDurationSeconds\x12/\n" +
	"\x13destroyed_buildings\x18\x04 \x01(\x05R\x12destroyedBuildings\x12'\n" +
	"\x0ftotal_buildings\x18\x05 \x01(\x05R\x0etotalBuildings\x12.\n" +
	"\x13town_hall_destroyed\x18\x06 \x01(\bR\x11townHallDestroyed\x12\x1f\n" +
	"\vlooted_gold\x18\a \x01(\x03R\n" +
	"lootedGold\x12#\n" +
	"\rlooted_elixir\x18\b \x01(\x03R\flootedElixir\x12,\n" +
	"\x12looted_dark_elixir\x18\t \x01(\x03R\x10lootedDarkElixir\"\xa6\x01\n" +
	"\rBattleRewards\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x03R\x04gold\x12\x16\n" +
	"\x06elixir\x18\x02 \x01(\x03R\x06elixir\x12\x1f\n" +
	"\vdark_elixir\x18\x03 \x01(\x03R\n" +
	"darkElixir\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x126\n" +
	"\vbonus_items\x18\x05 \x03(\v2\x15.battlesvr.ItemRewardR\n" +
	"bonusItems\"H\n" +
	"\n" +
	"ItemReward\x12$\n" +
	"\x0eitem_config_id\x18\x01 \x01(\x05R\fitemConfigId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xa0\x02\n" +
	"\fTrophyChange\x12.\n" +
	"\x13attacker_old_trophy\x18\x01 \x01(\x03R\x11attackerOldTrophy\x12.\n" +
	"\x13attacker_new_trophy\x18\x02 \x01(\x03R\x11attackerNewTrophy\x12'\n" +
	"\x0fattacker_change\x18\x03 \x01(\x05R\x0eattackerChange\x12.\n" +
	"\x13defender_old_trophy\x18\x04 \x01(\x03R\x11defenderOldTrophy\x12.\n" +
	"\x13defender_new_trophy\x18\x05 \x01(\x03R\x11defenderNewTrophy\x12'\n" +
	"\x0fdefender_change\x18\x06 \x01(\x05R\x0edefenderChange\"5\n" +
	"\x16GetBattleReplayRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\"~\n" +
	"\x17GetBattleReplayResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12<\n" +
	"\vreplay_data\x18\x02 \x01(\v2\x1b.battlesvr.BattleReplayDataR\n" +
	"replayData\"\xf9\x01\n" +
	"\x10BattleReplayData\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x126\n" +
	"\tinit_data\x18\x02 \x01(\v2\x19.battlesvr.BattleInitDataR\binitData\x121\n" +
	"\aactions\x18\x03 \x03(\v2\x17.battlesvr.BattleActionR\aactions\x12<\n" +
	"\vresult_data\x18\x04 \x01(\v2\x1b.battlesvr.BattleResultDataR\n" +
	"resultData\x12\x1f\n" +
	"\vbattle_time\x18\x05 \x01(\x03R\n" +
	"battleTime\"L\n" +
	"\x19GetMyAttackRecordsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x9c\x01\n" +
	"\x1aGetMyAttackRecordsResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x126\n" +
	"\arecords\x18\x02 \x03(\v2\x1c.battlesvr.BattleRecordBriefR\arecords\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"M\n" +
	"\x1aGetMyDefenseRecordsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x9d\x01\n" +
	"\x1bGetMyDefenseRecordsResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x126\n" +
	"\arecords\x18\x02 \x03(\v2\x1c.battlesvr.BattleRecordBriefR\arecords\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xbf\x03\n" +
	"\x11BattleRecordBrief\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12\x1f\n" +
	"\vopponent_id\x18\x02 \x01(\tR\n" +
	"opponentId\x12+\n" +
	"\x11opponent_username\x18\x03 \x01(\tR\x10opponentUsername\x12'\n" +
	"\x0fopponent_trophy\x18\x04 \x01(\x03R\x0eopponentTrophy\x12\x14\n" +
	"\x05stars\x18\x05 \x01(\x05R\x05stars\x125\n" +
	"\x16destruction_percentage\x18\x06 \x01(\x05R\x15destructionPercentage\x12#\n" +
	"\rtrophy_change\x18\a \x01(\x05R\ftrophyChange\x120\n" +
	"\x14resource_change_gold\x18\b \x01(\x03R\x12resourceChangeGold\x124\n" +
	"\x16resource_change_elixir\x18\t \x01(\x03R\x14resourceChangeElixir\x12\x1f\n" +
	"\vbattle_time\x18\n" +
	" \x01(\x03R\n" +
	"battleTime\x12\x1b\n" +
	"\tis_attack\x18\v \x01(\bR\bisAttack\"5\n" +
	"\x16GetBattleDetailRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\"~\n" +
	"\x17GetBattleDetailResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12<\n" +
	"\rbattle_detail\x18\x02 \x01(\v2\x17.battlesvr.BattleDetailR\fbattleDetail\"\xe0\x03\n" +
	"\fBattleDetail\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x03R\bbattleId\x12\x1f\n" +
	"\vattacker_id\x18\x02 \x01(\tR\n" +
	"attackerId\x12\x1f\n" +
	"\vdefender_id\x18\x03 \x01(\tR\n" +
	"defenderId\x126\n" +
	"\tinit_data\x18\x04 \x01(\v2\x19.battlesvr.BattleInitDataR\binitData\x121\n" +
	"\aactions\x18\x05 \x03(\v2\x17.battlesvr.BattleActionR\aactions\x12<\n" +
	"\vresult_data\x18\x06 \x01(\v2\x1b.battlesvr.BattleResultDataR\n" +
	"resultData\x122\n" +
	"\arewards\x18\a \x01(\v2\x18.battlesvr.BattleRewardsR\arewards\x12<\n" +
	"\rtrophy_change\x18\b \x01(\v2\x17.battlesvr.TrophyChangeR\ftrophyChange\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vfinished_at\x18\v \x01(\x03R\n" +
	"finishedAtBTZ;pitaya-game/protos/protobuf/pb/golang/battlesvr;battlesvrpb\xaa\x02\x14PitayaGame.BattleSvrb\x06proto3"

var (
	file_battlesvr_battle_proto_rawDescOnce sync.Once
	file_battlesvr_battle_proto_rawDescData []byte
)

func file_battlesvr_battle_proto_rawDescGZIP() []byte {
	file_battlesvr_battle_proto_rawDescOnce.Do(func() {
		file_battlesvr_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battlesvr_battle_proto_rawDesc), len(file_battlesvr_battle_proto_rawDesc)))
	})
	return file_battlesvr_battle_proto_rawDescData
}

var file_battlesvr_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_battlesvr_battle_proto_goTypes = []any{
	(*StartAttackRequest)(nil),          // 0: battlesvr.StartAttackRequest
	(*StartAttackResponse)(nil),         // 1: battlesvr.StartAttackResponse
	(*BattleInitData)(nil),              // 2: battlesvr.BattleInitData
	(*DefenderBaseData)(nil),            // 3: battlesvr.DefenderBaseData
	(*AttackerArmyData)(nil),            // 4: battlesvr.AttackerArmyData
	(*RecordBattleActionsRequest)(nil),  // 5: battlesvr.RecordBattleActionsRequest
	(*RecordBattleActionsResponse)(nil), // 6: battlesvr.RecordBattleActionsResponse
	(*BattleAction)(nil),                // 7: battlesvr.BattleAction
	(*SubmitBattleResultRequest)(nil),   // 8: battlesvr.SubmitBattleResultRequest
	(*SubmitBattleResultResponse)(nil),  // 9: battlesvr.SubmitBattleResultResponse
	(*BattleResultData)(nil),            // 10: battlesvr.BattleResultData
	(*BattleRewards)(nil),               // 11: battlesvr.BattleRewards
	(*ItemReward)(nil),                  // 12: battlesvr.ItemReward
	(*TrophyChange)(nil),                // 13: battlesvr.TrophyChange
	(*GetBattleReplayRequest)(nil),      // 14: battlesvr.GetBattleReplayRequest
	(*GetBattleReplayResponse)(nil),     // 15: battlesvr.GetBattleReplayResponse
	(*BattleReplayData)(nil),            // 16: battlesvr.BattleReplayData
	(*GetMyAttackRecordsRequest)(nil),   // 17: battlesvr.GetMyAttackRecordsRequest
	(*GetMyAttackRecordsResponse)(nil),  // 18: battlesvr.GetMyAttackRecordsResponse
	(*GetMyDefenseRecordsRequest)(nil),  // 19: battlesvr.GetMyDefenseRecordsRequest
	(*GetMyDefenseRecordsResponse)(nil), // 20: battlesvr.GetMyDefenseRecordsResponse
	(*BattleRecordBrief)(nil),           // 21: battlesvr.BattleRecordBrief
	(*GetBattleDetailRequest)(nil),      // 22: battlesvr.GetBattleDetailRequest
	(*GetBattleDetailResponse)(nil),     // 23: battlesvr.GetBattleDetailResponse
	(*BattleDetail)(nil),                // 24: battlesvr.BattleDetail
	(*types.CommonResp)(nil),            // 25: types.CommonResp
	(*types.Vector2)(nil),               // 26: types.Vector2
}
var file_battlesvr_battle_proto_depIdxs = []int32{
	25, // 0: battlesvr.StartAttackResponse.resp:type_name -> types.CommonResp
	2,  // 1: battlesvr.StartAttackResponse.init_data:type_name -> battlesvr.BattleInitData
	3,  // 2: battlesvr.BattleInitData.defender_base:type_name -> battlesvr.DefenderBaseData
	4,  // 3: battlesvr.BattleInitData.attacker_army:type_name -> battlesvr.AttackerArmyData
	7,  // 4: battlesvr.RecordBattleActionsRequest.actions:type_name -> battlesvr.BattleAction
	25, // 5: battlesvr.RecordBattleActionsResponse.resp:type_name -> types.CommonResp
	26, // 6: battlesvr.BattleAction.position:type_name -> types.Vector2
	10, // 7: battlesvr.SubmitBattleResultRequest.result_data:type_name -> battlesvr.BattleResultData
	25, // 8: battlesvr.SubmitBattleResultResponse.resp:type_name -> types.CommonResp
	11, // 9: battlesvr.SubmitBattleResultResponse.rewards:type_name -> battlesvr.BattleRewards
	13, // 10: battlesvr.SubmitBattleResultResponse.trophy_change:type_name -> battlesvr.TrophyChange
	12, // 11: battlesvr.BattleRewards.bonus_items:type_name -> battlesvr.ItemReward
	25, // 12: battlesvr.GetBattleReplayResponse.resp:type_name -> types.CommonResp
	16, // 13: battlesvr.GetBattleReplayResponse.replay_data:type_name -> battlesvr.BattleReplayData
	2,  // 14: battlesvr.BattleReplayData.init_data:type_name -> battlesvr.BattleInitData
	7,  // 15: battlesvr.BattleReplayData.actions:type_name -> battlesvr.BattleAction
	10, // 16: battlesvr.BattleReplayData.result_data:type_name -> battlesvr.BattleResultData
	25, // 17: battlesvr.GetMyAttackRecordsResponse.resp:type_name -> types.CommonResp
	21, // 18: battlesvr.GetMyAttackRecordsResponse.records:type_name -> battlesvr.BattleRecordBrief
	25, // 19: battlesvr.GetMyDefenseRecordsResponse.resp:type_name -> types.CommonResp
	21, // 20: battlesvr.GetMyDefenseRecordsResponse.records:type_name -> battlesvr.BattleRecordBrief
	25, // 21: battlesvr.GetBattleDetailResponse.resp:type_name -> types.CommonResp
	24, // 22: battlesvr.GetBattleDetailResponse.battle_detail:type_name -> battlesvr.BattleDetail
	2,  // 23: battlesvr.BattleDetail.init_data:type_name -> battlesvr.BattleInitData
	7,  // 24: battlesvr.BattleDetail.actions:type_name -> battlesvr.BattleAction
	10, // 25: battlesvr.BattleDetail.result_data:type_name -> battlesvr.BattleResultData
	11, // 26: battlesvr.BattleDetail.rewards:type_name -> battlesvr.BattleRewards
	13, // 27: battlesvr.BattleDetail.trophy_change:type_name -> battlesvr.TrophyChange
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_battlesvr_battle_proto_init() }
func file_battlesvr_battle_proto_init() {
	if File_battlesvr_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battlesvr_battle_proto_rawDesc), len(file_battlesvr_battle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_battlesvr_battle_proto_goTypes,
		DependencyIndexes: file_battlesvr_battle_proto_depIdxs,
		MessageInfos:      file_battlesvr_battle_proto_msgTypes,
	}.Build()
	File_battlesvr_battle_proto = out.File
	file_battlesvr_battle_proto_goTypes = nil
	file_battlesvr_battle_proto_depIdxs = nil
}
