// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: matchmakingsvr/match_coc.proto

package matchmakingsvrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取下一个匹配候选
type GetNextCandidateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExcludeDefenderIds []string               `protobuf:"bytes,1,rep,name=exclude_defender_ids,json=excludeDefenderIds,proto3" json:"exclude_defender_ids,omitempty"` // 排除的防御者ID列表
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetNextCandidateRequest) Reset() {
	*x = GetNextCandidateRequest{}
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextCandidateRequest) ProtoMessage() {}

func (x *GetNextCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextCandidateRequest.ProtoReflect.Descriptor instead.
func (*GetNextCandidateRequest) Descriptor() ([]byte, []int) {
	return file_matchmakingsvr_match_coc_proto_rawDescGZIP(), []int{0}
}

func (x *GetNextCandidateRequest) GetExcludeDefenderIds() []string {
	if x != nil {
		return x.ExcludeDefenderIds
	}
	return nil
}

type GetNextCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Candidate     *CandidateData         `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	MatchId       int64                  `protobuf:"varint,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // 匹配ID（创建占用记录时生成，用于战斗服务识别客户端选择的匹配，且必须是该攻击者自己刷出来的）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextCandidateResponse) Reset() {
	*x = GetNextCandidateResponse{}
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextCandidateResponse) ProtoMessage() {}

func (x *GetNextCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextCandidateResponse.ProtoReflect.Descriptor instead.
func (*GetNextCandidateResponse) Descriptor() ([]byte, []int) {
	return file_matchmakingsvr_match_coc_proto_rawDescGZIP(), []int{1}
}

func (x *GetNextCandidateResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetNextCandidateResponse) GetCandidate() *CandidateData {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *GetNextCandidateResponse) GetMatchId() int64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

// 候选对手（服务端已排除受保护目标）
type CandidateData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DefenderId         string                 `protobuf:"bytes,1,opt,name=defender_id,json=defenderId,proto3" json:"defender_id,omitempty"`
	DefenderUsername   string                 `protobuf:"bytes,2,opt,name=defender_username,json=defenderUsername,proto3" json:"defender_username,omitempty"` // 可选：未接入用户服务前可回传ID
	DefenderTrophy     int64                  `protobuf:"varint,3,opt,name=defender_trophy,json=defenderTrophy,proto3" json:"defender_trophy,omitempty"`
	DefenderBasePower  int32                  `protobuf:"varint,4,opt,name=defender_base_power,json=defenderBasePower,proto3" json:"defender_base_power,omitempty"`
	BaseSnapshot       *BaseSnapshotView      `protobuf:"bytes,5,opt,name=base_snapshot,json=baseSnapshot,proto3" json:"base_snapshot,omitempty"`                      // 基地布局快照
	SnapshotUpdateTime int64                  `protobuf:"varint,6,opt,name=snapshot_update_time,json=snapshotUpdateTime,proto3" json:"snapshot_update_time,omitempty"` // Unix秒（BaseSnapshot.updated_at）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CandidateData) Reset() {
	*x = CandidateData{}
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateData) ProtoMessage() {}

func (x *CandidateData) ProtoReflect() protoreflect.Message {
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateData.ProtoReflect.Descriptor instead.
func (*CandidateData) Descriptor() ([]byte, []int) {
	return file_matchmakingsvr_match_coc_proto_rawDescGZIP(), []int{2}
}

func (x *CandidateData) GetDefenderId() string {
	if x != nil {
		return x.DefenderId
	}
	return ""
}

func (x *CandidateData) GetDefenderUsername() string {
	if x != nil {
		return x.DefenderUsername
	}
	return ""
}

func (x *CandidateData) GetDefenderTrophy() int64 {
	if x != nil {
		return x.DefenderTrophy
	}
	return 0
}

func (x *CandidateData) GetDefenderBasePower() int32 {
	if x != nil {
		return x.DefenderBasePower
	}
	return 0
}

func (x *CandidateData) GetBaseSnapshot() *BaseSnapshotView {
	if x != nil {
		return x.BaseSnapshot
	}
	return nil
}

func (x *CandidateData) GetSnapshotUpdateTime() int64 {
	if x != nil {
		return x.SnapshotUpdateTime
	}
	return 0
}

// 基地快照视图（从 BaseSnapshot 透传，默认 bytes 承载 JSON/压缩串）
type BaseSnapshotView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LayoutData    []byte                 `protobuf:"bytes,1,opt,name=layout_data,json=layoutData,proto3" json:"layout_data,omitempty"`           // BaseSnapshot.base_data（JSON或压缩）
	LayoutVersion int32                  `protobuf:"varint,2,opt,name=layout_version,json=layoutVersion,proto3" json:"layout_version,omitempty"` // 与客户端约定的布局版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSnapshotView) Reset() {
	*x = BaseSnapshotView{}
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSnapshotView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSnapshotView) ProtoMessage() {}

func (x *BaseSnapshotView) ProtoReflect() protoreflect.Message {
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSnapshotView.ProtoReflect.Descriptor instead.
func (*BaseSnapshotView) Descriptor() ([]byte, []int) {
	return file_matchmakingsvr_match_coc_proto_rawDescGZIP(), []int{3}
}

func (x *BaseSnapshotView) GetLayoutData() []byte {
	if x != nil {
		return x.LayoutData
	}
	return nil
}

func (x *BaseSnapshotView) GetLayoutVersion() int32 {
	if x != nil {
		return x.LayoutVersion
	}
	return 0
}

// 取消匹配（玩家放弃所有通过 GetNextCandidate 锁定的匹配，删除所有 pending 匹配记录）
type CancelMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchRequest) Reset() {
	*x = CancelMatchRequest{}
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchRequest) ProtoMessage() {}

func (x *CancelMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchRequest.ProtoReflect.Descriptor instead.
func (*CancelMatchRequest) Descriptor() ([]byte, []int) {
	return file_matchmakingsvr_match_coc_proto_rawDescGZIP(), []int{4}
}

type CancelMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchResponse) Reset() {
	*x = CancelMatchResponse{}
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchResponse) ProtoMessage() {}

func (x *CancelMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmakingsvr_match_coc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchResponse.ProtoReflect.Descriptor instead.
func (*CancelMatchResponse) Descriptor() ([]byte, []int) {
	return file_matchmakingsvr_match_coc_proto_rawDescGZIP(), []int{5}
}

func (x *CancelMatchResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

var File_matchmakingsvr_match_coc_proto protoreflect.FileDescriptor

const file_matchmakingsvr_match_coc_proto_rawDesc = "" +
	"\n" +
	"\x1ematchmakingsvr/match_coc.proto\x12\x0ematchmakingsvr\x1a\x18common/types/types.proto\"K\n" +
	"\x17GetNextCandidateRequest\x120\n" +
	"\x14exclude_defender_ids\x18\x01 \x03(\tR\x12excludeDefenderIds\"\x99\x01\n" +
	"\x18GetNextCandidateResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12;\n" +
	"\tcandidate\x18\x02 \x01(\v2\x1d.matchmakingsvr.CandidateDataR\tcandidate\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\x03R\amatchId\"\xaf\x02\n" +
	"\rCandidateData\x12\x1f\n" +
	"\vdefender_id\x18\x01 \x01(\tR\n" +
	"defenderId\x12+\n" +
	"\x11defender_username\x18\x02 \x01(\tR\x10defenderUsername\x12'\n" +
	"\x0fdefender_trophy\x18\x03 \x01(\x03R\x0edefenderTrophy\x12.\n" +
	"\x13defender_base_power\x18\x04 \x01(\x05R\x11defenderBasePower\x12E\n" +
	"\rbase_snapshot\x18\x05 \x01(\v2 .matchmakingsvr.BaseSnapshotViewR\fbaseSnapshot\x120\n" +
	"\x14snapshot_update_time\x18\x06 \x01(\x03R\x12snapshotUpdateTime\"Z\n" +
	"\x10BaseSnapshotView\x12\x1f\n" +
	"\vlayout_data\x18\x01 \x01(\fR\n" +
	"layoutData\x12%\n" +
	"\x0elayout_version\x18\x02 \x01(\x05R\rlayoutVersion\"\x14\n" +
	"\x12CancelMatchRequest\"<\n" +
	"\x13CancelMatchResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04respBcZEpitaya-game/protos/protobuf/pb/golang/matchmakingsvr;matchmakingsvrpb\xaa\x02\x19PitayaGame.MatchMakingSvrb\x06proto3"

var (
	file_matchmakingsvr_match_coc_proto_rawDescOnce sync.Once
	file_matchmakingsvr_match_coc_proto_rawDescData []byte
)

func file_matchmakingsvr_match_coc_proto_rawDescGZIP() []byte {
	file_matchmakingsvr_match_coc_proto_rawDescOnce.Do(func() {
		file_matchmakingsvr_match_coc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchmakingsvr_match_coc_proto_rawDesc), len(file_matchmakingsvr_match_coc_proto_rawDesc)))
	})
	return file_matchmakingsvr_match_coc_proto_rawDescData
}

var file_matchmakingsvr_match_coc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_matchmakingsvr_match_coc_proto_goTypes = []any{
	(*GetNextCandidateRequest)(nil),  // 0: matchmakingsvr.GetNextCandidateRequest
	(*GetNextCandidateResponse)(nil), // 1: matchmakingsvr.GetNextCandidateResponse
	(*CandidateData)(nil),            // 2: matchmakingsvr.CandidateData
	(*BaseSnapshotView)(nil),         // 3: matchmakingsvr.BaseSnapshotView
	(*CancelMatchRequest)(nil),       // 4: matchmakingsvr.CancelMatchRequest
	(*CancelMatchResponse)(nil),      // 5: matchmakingsvr.CancelMatchResponse
	(*types.CommonResp)(nil),         // 6: types.CommonResp
}
var file_matchmakingsvr_match_coc_proto_depIdxs = []int32{
	6, // 0: matchmakingsvr.GetNextCandidateResponse.resp:type_name -> types.CommonResp
	2, // 1: matchmakingsvr.GetNextCandidateResponse.candidate:type_name -> matchmakingsvr.CandidateData
	3, // 2: matchmakingsvr.CandidateData.base_snapshot:type_name -> matchmakingsvr.BaseSnapshotView
	6, // 3: matchmakingsvr.CancelMatchResponse.resp:type_name -> types.CommonResp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_matchmakingsvr_match_coc_proto_init() }
func file_matchmakingsvr_match_coc_proto_init() {
	if File_matchmakingsvr_match_coc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchmakingsvr_match_coc_proto_rawDesc), len(file_matchmakingsvr_match_coc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchmakingsvr_match_coc_proto_goTypes,
		DependencyIndexes: file_matchmakingsvr_match_coc_proto_depIdxs,
		MessageInfos:      file_matchmakingsvr_match_coc_proto_msgTypes,
	}.Build()
	File_matchmakingsvr_match_coc_proto = out.File
	file_matchmakingsvr_match_coc_proto_goTypes = nil
	file_matchmakingsvr_match_coc_proto_depIdxs = nil
}
