// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common/errors/errors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PitayaGame.Errors {

  /// <summary>Holder for reflection information generated from common/errors/errors.proto</summary>
  public static partial class ErrorsReflection {

    #region Descriptor
    /// <summary>File descriptor for common/errors/errors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chpjb21tb24vZXJyb3JzL2Vycm9ycy5wcm90bxIGZXJyb3JzGiBnb29nbGUv",
            "cHJvdG9idWYvZGVzY3JpcHRvci5wcm90byqWLAoJRXJyb3JDb2RlEigKB1NV",
            "Q0NFU1MQABobirUYDOaTjeS9nOaIkOWKn5K1GAdTdWNjZXNzEjMKC0VSUl9V",
            "TktOT1dOEOgHGiGKtRgM5pyq55+l6ZSZ6K+vkrUYDVVua25vd24gZXJyb3IS",
            "PQoRRVJSX0lOVkFMSURfUEFSQU0Q6QcaJYq1GAzlj4LmlbDplJnor6+StRgR",
            "SW52YWxpZCBwYXJhbWV0ZXISMwoLRVJSX05FVFdPUksQ6gcaIYq1GAznvZHn",
            "u5zplJnor6+StRgNTmV0d29yayBlcnJvchI1CgtFUlJfVElNRU9VVBDrBxoj",
            "irUYDOivt+axgui2heaXtpK1GA9SZXF1ZXN0IHRpbWVvdXQSPQoNRVJSX05P",
            "VF9GT1VORBDsBxopirUYD+i1hOa6kOS4jeWtmOWcqJK1GBJSZXNvdXJjZSBu",
            "b3QgZm91bmQSRwoSRVJSX0FMUkVBRFlfRVhJU1RTEO0HGi6KtRgP6LWE5rqQ",
            "5bey5a2Y5ZyokrUYF1Jlc291cmNlIGFscmVhZHkgZXhpc3RzEkEKFUVSUl9Q",
            "RVJNSVNTSU9OX0RFTklFRBDuBxolirUYDOadg+mZkOS4jei2s5K1GBFQZXJt",
            "aXNzaW9uIGRlbmllZBJCCg5FUlJfUkFURV9MSU1JVBDvBxotirUYEuivt+ax",
            "gui/h+S6jumikee5gZK1GBNSYXRlIGxpbWl0IGV4Y2VlZGVkEj0KFkVSUl9B",
            "VVRIX0lOVkFMSURfVE9LRU4Q0A8aIIq1GAtUb2tlbuaXoOaViJK1GA1JbnZh",
            "bGlkIHRva2VuEkAKFkVSUl9BVVRIX1RPS0VOX0VYUElSRUQQ0Q8aI4q1GA5U",
            "b2tlbuW3sui/h+acn5K1GA1Ub2tlbiBleHBpcmVkEkgKG0VSUl9BVVRIX0lO",
            "VkFMSURfQ1JFREVOVElBTBDSDxomirUYDOWHreivgeaXoOaViJK1GBJJbnZh",
            "bGlkIGNyZWRlbnRpYWwSQwoXRVJSX0FVVEhfVVNFUl9OT1RfRk9VTkQQ0w8a",
            "JYq1GA/nlKjmiLfkuI3lrZjlnKiStRgOVXNlciBub3QgZm91bmQSRQoURVJS",
            "X0FVVEhfVVNFUl9FWElTVFMQ1A8aKoq1GA/nlKjmiLflt7LlrZjlnKiStRgT",
            "VXNlciBhbHJlYWR5IGV4aXN0cxJAChdFUlJfQVVUSF9QQVNTV09SRF9XUk9O",
            "RxDVDxoiirUYDOWvhueggemUmeivr5K1GA5Xcm9uZyBwYXNzd29yZBJFChhF",
            "UlJfQVVUSF9TRVNTSU9OX0VYUElSRUQQ1g8aJoq1GA/kvJror53lt7Lov4fm",
            "nJ+StRgPU2Vzc2lvbiBleHBpcmVkEmwKGkVSUl9BVVRIX1NFU1NJT05fTk9U",
            "X0ZPVU5EENcPGkuKtRge5Lya6K+d5LiN5a2Y5Zyo77yM6K+35YWI55m75b2V",
            "krUYJVNlc3Npb24gbm90IGZvdW5kLCBwbGVhc2UgbG9naW4gZmlyc3QSPgoS",
            "RVJSX1VTRVJfTk9UX0ZPVU5EELgXGiWKtRgP55So5oi35LiN5a2Y5ZyokrUY",
            "DlVzZXIgbm90IGZvdW5kEjsKD0VSUl9VU0VSX0JBTk5FRBC5FxolirUYEueU",
            "qOaIt+W3suiiq+WwgeemgZK1GAtVc2VyIGJhbm5lZBJOCh5FUlJfVVNFUl9J",
            "TlNVRkZJQ0lFTlRfUkVTT1VSQ0UQuhcaKYq1GAzotYTmupDkuI3otrOStRgV",
            "SW5zdWZmaWNpZW50IHJlc291cmNlEkQKGUVSUl9VU0VSX0xFVkVMX05PVF9F",
            "Tk9VR0gQuxcaJIq1GAznrYnnuqfkuI3otrOStRgQTGV2ZWwgbm90IGVub3Vn",
            "aBJLChlFUlJfVVNFUl9JTlNVRkZJQ0lFTlRfRVhQELwXGiuKtRgM57uP6aqM",
            "5LiN6LazkrUYF0luc3VmZmljaWVudCBleHBlcmllbmNlEkgKG0VSUl9VU0VS",
            "X0lOU1VGRklDSUVOVF9DT0lOUxC9FxomirUYDOmHkeW4geS4jei2s5K1GBJJ",
            "bnN1ZmZpY2llbnQgY29pbnMSSAoXRVJSX0NIQVJBQ1RFUl9OT1RfRk9VTkQQ",
            "oB8aKoq1GA/op5LoibLkuI3lrZjlnKiStRgTQ2hhcmFjdGVyIG5vdCBmb3Vu",
            "ZBJJChdFUlJfQ0hBUkFDVEVSX0xFVkVMX01BWBChHxorirUYEuW3sui+vuac",
            "gOWkp+etiee6p5K1GBFNYXggbGV2ZWwgcmVhY2hlZBJQCh5FUlJfQ0hBUkFD",
            "VEVSX0lOU1VGRklDSUVOVF9FWFAQoh8aK4q1GAznu4/pqozkuI3otrOStRgX",
            "SW5zdWZmaWNpZW50IGV4cGVyaWVuY2USPgoSRVJSX0hFUk9fTk9UX0ZPVU5E",
            "EIQgGiWKtRgP6Iux6ZuE5LiN5a2Y5ZyokrUYDkhlcm8gbm90IGZvdW5kEkwK",
            "GUVSUl9IRVJPX0FMUkVBRFlfREVQTE9ZRUQQhSAaLIq1GA/oi7Hpm4Tlt7Lk",
            "uIrpmLWStRgVSGVybyBhbHJlYWR5IGRlcGxveWVkEkQKFUVSUl9IRVJPX05P",
            "VF9ERVBMT1lFRBCGIBooirUYD+iLsembhOacquS4iumYtZK1GBFIZXJvIG5v",
            "dCBkZXBsb3llZBJPChJFUlJfSEVST19NQVhfTEVWRUwQhyAaNoq1GBjoi7Hp",
            "m4Tlt7Lovr7mnIDlpKfnrYnnuqeStRgWSGVybyBtYXggbGV2ZWwgcmVhY2hl",
            "ZBJEChVFUlJfU09MRElFUl9OT1RfRk9VTkQQ6CAaKIq1GA/lo6vlhbXkuI3l",
            "rZjlnKiStRgRU29sZGllciBub3QgZm91bmQSUgocRVJSX1NPTERJRVJfQUxS",
            "RUFEWV9ERVBMT1lFRBDpIBovirUYD+Wjq+WFteW3suS4iumYtZK1GBhTb2xk",
            "aWVyIGFscmVhZHkgZGVwbG95ZWQSSgoYRVJSX1NPTERJRVJfTk9UX0RFUExP",
            "WUVEEOogGiuKtRgP5aOr5YW15pyq5LiK6Zi1krUYFFNvbGRpZXIgbm90IGRl",
            "cGxveWVkElUKFUVSUl9TT0xESUVSX01BWF9MRVZFTBDrIBo5irUYGOWjq+WF",
            "teW3sui+vuacgOWkp+etiee6p5K1GBlTb2xkaWVyIG1heCBsZXZlbCByZWFj",
            "aGVkEkgKF0VSUl9NRVJDRU5BUllfTk9UX0ZPVU5EEMwhGiqKtRgP5L2j5YW1",
            "5LiN5a2Y5ZyokrUYE01lcmNlbmFyeSBub3QgZm91bmQSVgoeRVJSX01FUkNF",
            "TkFSWV9BTFJFQURZX0RFUExPWUVEEM0hGjGKtRgP5L2j5YW15bey5LiK6Zi1",
            "krUYGk1lcmNlbmFyeSBhbHJlYWR5IGRlcGxveWVkEk4KGkVSUl9NRVJDRU5B",
            "UllfTk9UX0RFUExPWUVEEM4hGi2KtRgP5L2j5YW15pyq5LiK6Zi1krUYFk1l",
            "cmNlbmFyeSBub3QgZGVwbG95ZWQSWQoXRVJSX01FUkNFTkFSWV9NQVhfTEVW",
            "RUwQzyEaO4q1GBjkvaPlhbXlt7Lovr7mnIDlpKfnrYnnuqeStRgbTWVyY2Vu",
            "YXJ5IG1heCBsZXZlbCByZWFjaGVkEkYKFkVSUl9CVUlMRElOR19OT1RfRk9V",
            "TkQQiCcaKYq1GA/lu7rnrZHkuI3lrZjlnKiStRgSQnVpbGRpbmcgbm90IGZv",
            "dW5kElkKFkVSUl9CVUlMRElOR19NQVhfQ09VTlQQiScaPIq1GBjlu7rnrZHm",
            "lbDph4/lt7Lovr7kuIrpmZCStRgcQnVpbGRpbmcgY291bnQgbGltaXQgcmVh",
            "Y2hlZBJsChtFUlJfQlVJTERJTkdfVFlQRV9NQVhfQ09VTlQQiicaSoq1GCHo",
            "r6Xnsbvlnovlu7rnrZHmlbDph4/lt7Lovr7kuIrpmZCStRghQnVpbGRpbmcg",
            "dHlwZSBjb3VudCBsaW1pdCByZWFjaGVkElcKFkVSUl9CVUlMRElOR19NQVhf",
            "TEVWRUwQiycaOoq1GBjlu7rnrZHlt7Lovr7mnIDlpKfnrYnnuqeStRgaQnVp",
            "bGRpbmcgbWF4IGxldmVsIHJlYWNoZWQSTwoWRVJSX0JVSUxESU5HX1VQR1JB",
            "RElORxCMJxoyirUYFeW7uuetkeato+WcqOWNh+e6p+S4rZK1GBVCdWlsZGlu",
            "ZyBpcyB1cGdyYWRpbmcSWAoeRVJSX0JVSUxESU5HX1BPU0lUSU9OX09DQ1VQ",
            "SUVEEI0nGjOKtRgS5L2N572u5bey6KKr5Y2g55SokrUYGVBvc2l0aW9uIGFs",
            "cmVhZHkgb2NjdXBpZWQSWgodRVJSX0JVSUxESU5HX0NPTkZJR19OT1RfRk9V",
            "TkQQjicaNoq1GBXlu7rnrZHphY3nva7kuI3lrZjlnKiStRgZQnVpbGRpbmcg",
            "Y29uZmlnIG5vdCBmb3VuZBJsCiNFUlJfQlVJTERJTkdfTEVWRUxfQ09ORklH",
            "X05PVF9GT1VORBCPJxpCirUYG+W7uuetkeetiee6p+mFjee9ruS4jeWtmOWc",
            "qJK1GB9CdWlsZGluZyBsZXZlbCBjb25maWcgbm90IGZvdW5kEmsKHkVSUl9C",
            "VUlMRElOR19DT05ESVRJT05fTk9UX01FVBCQJxpGirUYHOW7uumAoC/ljYfn",
            "uqfmnaHku7bkuI3mu6HotrOStRgiQnVpbGRpbmcvdXBncmFkZSBjb25kaXRp",
            "b24gbm90IG1ldBJYChxFUlJfQlVJTERJTkdfTEVWRUxfTk9UX0ZPVU5EEJEn",
            "GjWKtRgV5bu6562R562J57qn5LiN5a2Y5ZyokrUYGEJ1aWxkaW5nIGxldmVs",
            "IG5vdCBmb3VuZBI+ChJFUlJfQVJNWV9OT1RfRk9VTkQQ7CcaJYq1GA/lhpvp",
            "mJ/kuI3lrZjlnKiStRgOQXJteSBub3QgZm91bmQSMQoNRVJSX0FSTVlfRlVM",
            "TBDtJxodirUYDOWGm+mYn+W3sua7oZK1GAlBcm15IGZ1bGwSTwoWRVJSX0FS",
            "TVlfTElNSVRfUkVBQ0hFRBDuJxoyirUYGOWGm+mYn+aVsOmHj+W3sui+vuS4",
            "iumZkJK1GBJBcm15IGxpbWl0IHJlYWNoZWQSQAoTRVJSX1NQRUxMX05PVF9G",
            "T1VORBDQKBomirUYD+azleacr+S4jeWtmOWcqJK1GA9TcGVsbCBub3QgZm91",
            "bmQSTgoaRVJSX1NQRUxMX0FMUkVBRFlfREVQTE9ZRUQQ0SgaLYq1GA/ms5Xm",
            "nK/lt7Lpg6jnvbKStRgWU3BlbGwgYWxyZWFkeSBkZXBsb3llZBJGChZFUlJf",
            "U1BFTExfTk9UX0RFUExPWUVEENIoGimKtRgP5rOV5pyv5pyq6YOo572ykrUY",
            "ElNwZWxsIG5vdCBkZXBsb3llZBJRChNFUlJfU1BFTExfTUFYX0xFVkVMENMo",
            "GjeKtRgY5rOV5pyv5bey6L6+5pyA5aSn562J57qnkrUYF1NwZWxsIG1heCBs",
            "ZXZlbCByZWFjaGVkEk4KGkVSUl9TUEVMTF9BTFJFQURZX1VOTE9DS0VEENQo",
            "Gi2KtRgP5rOV5pyv5bey6Kej6ZSBkrUYFlNwZWxsIGFscmVhZHkgdW5sb2Nr",
            "ZWQSOwoSRVJSX0lOVkVOVE9SWV9GVUxMEPAuGiKKtRgM6IOM5YyF5bey5ruh",
            "krUYDkludmVudG9yeSBmdWxsEkgKHEVSUl9JTlZFTlRPUllfSVRFTV9OT1Rf",
            "Rk9VTkQQ8S4aJYq1GA/nianlk4HkuI3lrZjlnKiStRgOSXRlbSBub3QgZm91",
            "bmQSWQojRVJSX0lOVkVOVE9SWV9JTlNVRkZJQ0lFTlRfUVVBTlRJVFkQ8i4a",
            "L4q1GBLnianlk4HmlbDph4/kuI3otrOStRgVSW5zdWZmaWNpZW50IHF1YW50",
            "aXR5EloKF0VSUl9JTlZFTlRPUllfVVNFX0xJTUlUEPMuGjyKtRge54mp5ZOB",
            "5L2/55So5qyh5pWw5bey6L6+5LiK6ZmQkrUYFkl0ZW0gdXNlIGxpbWl0IHJl",
            "YWNoZWQSTgoaRVJSX01BVENIX0FMUkVBRFlfSU5fUVVFVUUQ2DYaLYq1GBXl",
            "t7LlnKjljLnphY3pmJ/liJfkuK2StRgQQWxyZWFkeSBpbiBxdWV1ZRJGChZF",
            "UlJfTUFUQ0hfTk9UX0lOX1FVRVVFENk2GimKtRgV5LiN5Zyo5Yy56YWN6Zif",
            "5YiX5LitkrUYDE5vdCBpbiBxdWV1ZRI5ChFFUlJfTUFUQ0hfVElNRU9VVBDa",
            "NhohirUYDOWMuemFjei2heaXtpK1GA1NYXRjaCB0aW1lb3V0EkAKE0VSUl9N",
            "QVRDSF9DQU5DRUxMRUQQ2zYaJoq1GA/ljLnphY3lt7Llj5bmtoiStRgPTWF0",
            "Y2ggY2FuY2VsbGVkEkIKFEVSUl9CQVRUTEVfTk9UX0ZPVU5EEMA+GieKtRgP",
            "5oiY5paX5LiN5a2Y5ZyokrUYEEJhdHRsZSBub3QgZm91bmQSTgoaRVJSX0JB",
            "VFRMRV9BTFJFQURZX1NUQVJURUQQwT4aLYq1GA/miJjmlpflt7LlvIDlp4uS",
            "tRgWQmF0dGxlIGFscmVhZHkgc3RhcnRlZBJGChZFUlJfQkFUVExFX05PVF9T",
            "VEFSVEVEEMI+GimKtRgP5oiY5paX5pyq5byA5aeLkrUYEkJhdHRsZSBub3Qg",
            "c3RhcnRlZBI6ChBFUlJfQkFUVExFX0VOREVEEMM+GiOKtRgP5oiY5paX5bey",
            "57uT5p2fkrUYDEJhdHRsZSBlbmRlZBJSChlFUlJfQkFUVExFX0lOVkFMSURf",
            "QUNUSU9OEMQ+GjKKtRgV5peg5pWI55qE5oiY5paX5pON5L2ckrUYFUludmFs",
            "aWQgYmF0dGxlIGFjdGlvbhJGChZFUlJfU1lTVEVNX01BSU5URU5BTkNFEKhG",
            "GimKtRgP57O757uf57u05oqk5LitkrUYElN5c3RlbSBtYWludGVuYW5jZRI9",
            "ChNFUlJfU1lTVEVNX09WRVJMT0FEEKlGGiOKtRgM57O757uf57mB5b+ZkrUY",
            "D1N5c3RlbSBvdmVybG9hZBJCChRFUlJfQ09ORklHX05PVF9GT1VORBCqRhon",
            "irUYD+mFjee9ruS4jeWtmOWcqJK1GBBDb25maWcgbm90IGZvdW5kElEKGkVS",
            "Ul9DT05GSUdfSU5WQUxJRF9WRVJTSU9OEKtGGjCKtRgS6YWN572u54mI5pys",
            "5peg5pWIkrUYFkludmFsaWQgY29uZmlnIHZlcnNpb24SPAoTRVJSX1NZU1RF",
            "TV9JTlRFUk5BTBCPThoiirUYDOezu+e7n+mUmeivr5K1GA5JbnRlcm5hbCBl",
            "cnJvchJgCiVFUlJfQklHTUFQTUFSQ0hfQUxMT0NBVEVfTUFSQ0hJRF9GQUlM",
            "EJBOGjSKtRgU6I635Y+W6KGM5YabaWTlpLHotKWStRgYYWxsb2NhdGUgbWFy",
            "Y2ggaWQgZmFpbGVkOjoKDWVycm9yX21lc3NhZ2USIS5nb29nbGUucHJvdG9i",
            "dWYuRW51bVZhbHVlT3B0aW9ucxjRhgMgASgJOj0KEGVycm9yX21lc3NhZ2Vf",
            "ZW4SIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9ucxjShgMgASgJ",
            "QlJaPHBpdGF5YS1nYW1lL3Byb3Rvcy9wcm90b2J1Zi9wYi9nb2xhbmcvY29t",
            "bW9uL2Vycm9ycztlcnJvcnNwYqoCEVBpdGF5YUdhbWUuRXJyb3JzYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PitayaGame.Errors.ErrorCode), }, new pb::Extension[] { ErrorsExtensions.ErrorMessage, ErrorsExtensions.ErrorMessageEn }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of common/errors/errors.proto</summary>
  public static partial class ErrorsExtensions {
    /// <summary>
    /// 错误描述（中文）
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string> ErrorMessage =
      new pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string>(50001, pb::FieldCodec.ForString(400010, ""));
    /// <summary>
    /// 错误描述（英文）
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string> ErrorMessageEn =
      new pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string>(50002, pb::FieldCodec.ForString(400018, ""));
  }

  #region Enums
  public enum ErrorCode {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 0,
    /// <summary>
    /// 通用错误 (1000-1999)
    /// </summary>
    [pbr::OriginalName("ERR_UNKNOWN")] ErrUnknown = 1000,
    [pbr::OriginalName("ERR_INVALID_PARAM")] ErrInvalidParam = 1001,
    [pbr::OriginalName("ERR_NETWORK")] ErrNetwork = 1002,
    [pbr::OriginalName("ERR_TIMEOUT")] ErrTimeout = 1003,
    [pbr::OriginalName("ERR_NOT_FOUND")] ErrNotFound = 1004,
    [pbr::OriginalName("ERR_ALREADY_EXISTS")] ErrAlreadyExists = 1005,
    [pbr::OriginalName("ERR_PERMISSION_DENIED")] ErrPermissionDenied = 1006,
    [pbr::OriginalName("ERR_RATE_LIMIT")] ErrRateLimit = 1007,
    /// <summary>
    /// 认证错误 (2000-2999)
    /// </summary>
    [pbr::OriginalName("ERR_AUTH_INVALID_TOKEN")] ErrAuthInvalidToken = 2000,
    [pbr::OriginalName("ERR_AUTH_TOKEN_EXPIRED")] ErrAuthTokenExpired = 2001,
    [pbr::OriginalName("ERR_AUTH_INVALID_CREDENTIAL")] ErrAuthInvalidCredential = 2002,
    [pbr::OriginalName("ERR_AUTH_USER_NOT_FOUND")] ErrAuthUserNotFound = 2003,
    [pbr::OriginalName("ERR_AUTH_USER_EXISTS")] ErrAuthUserExists = 2004,
    [pbr::OriginalName("ERR_AUTH_PASSWORD_WRONG")] ErrAuthPasswordWrong = 2005,
    [pbr::OriginalName("ERR_AUTH_SESSION_EXPIRED")] ErrAuthSessionExpired = 2006,
    [pbr::OriginalName("ERR_AUTH_SESSION_NOT_FOUND")] ErrAuthSessionNotFound = 2007,
    /// <summary>
    /// 用户错误 (3000-3999)
    /// </summary>
    [pbr::OriginalName("ERR_USER_NOT_FOUND")] ErrUserNotFound = 3000,
    [pbr::OriginalName("ERR_USER_BANNED")] ErrUserBanned = 3001,
    [pbr::OriginalName("ERR_USER_INSUFFICIENT_RESOURCE")] ErrUserInsufficientResource = 3002,
    [pbr::OriginalName("ERR_USER_LEVEL_NOT_ENOUGH")] ErrUserLevelNotEnough = 3003,
    [pbr::OriginalName("ERR_USER_INSUFFICIENT_EXP")] ErrUserInsufficientExp = 3004,
    [pbr::OriginalName("ERR_USER_INSUFFICIENT_COINS")] ErrUserInsufficientCoins = 3005,
    /// <summary>
    /// 游戏单位错误 (4000-4999)
    /// 角色通用错误 (4000-4099)
    /// </summary>
    [pbr::OriginalName("ERR_CHARACTER_NOT_FOUND")] ErrCharacterNotFound = 4000,
    [pbr::OriginalName("ERR_CHARACTER_LEVEL_MAX")] ErrCharacterLevelMax = 4001,
    [pbr::OriginalName("ERR_CHARACTER_INSUFFICIENT_EXP")] ErrCharacterInsufficientExp = 4002,
    /// <summary>
    /// 英雄错误 (4100-4199)
    /// </summary>
    [pbr::OriginalName("ERR_HERO_NOT_FOUND")] ErrHeroNotFound = 4100,
    [pbr::OriginalName("ERR_HERO_ALREADY_DEPLOYED")] ErrHeroAlreadyDeployed = 4101,
    [pbr::OriginalName("ERR_HERO_NOT_DEPLOYED")] ErrHeroNotDeployed = 4102,
    [pbr::OriginalName("ERR_HERO_MAX_LEVEL")] ErrHeroMaxLevel = 4103,
    /// <summary>
    /// 士兵错误 (4200-4299)
    /// </summary>
    [pbr::OriginalName("ERR_SOLDIER_NOT_FOUND")] ErrSoldierNotFound = 4200,
    [pbr::OriginalName("ERR_SOLDIER_ALREADY_DEPLOYED")] ErrSoldierAlreadyDeployed = 4201,
    [pbr::OriginalName("ERR_SOLDIER_NOT_DEPLOYED")] ErrSoldierNotDeployed = 4202,
    [pbr::OriginalName("ERR_SOLDIER_MAX_LEVEL")] ErrSoldierMaxLevel = 4203,
    /// <summary>
    /// 佣兵错误 (4300-4399)
    /// </summary>
    [pbr::OriginalName("ERR_MERCENARY_NOT_FOUND")] ErrMercenaryNotFound = 4300,
    [pbr::OriginalName("ERR_MERCENARY_ALREADY_DEPLOYED")] ErrMercenaryAlreadyDeployed = 4301,
    [pbr::OriginalName("ERR_MERCENARY_NOT_DEPLOYED")] ErrMercenaryNotDeployed = 4302,
    [pbr::OriginalName("ERR_MERCENARY_MAX_LEVEL")] ErrMercenaryMaxLevel = 4303,
    /// <summary>
    /// 游戏功能错误 (5000-5999)
    /// 建筑错误 (5000-5099)
    /// </summary>
    [pbr::OriginalName("ERR_BUILDING_NOT_FOUND")] ErrBuildingNotFound = 5000,
    [pbr::OriginalName("ERR_BUILDING_MAX_COUNT")] ErrBuildingMaxCount = 5001,
    [pbr::OriginalName("ERR_BUILDING_TYPE_MAX_COUNT")] ErrBuildingTypeMaxCount = 5002,
    [pbr::OriginalName("ERR_BUILDING_MAX_LEVEL")] ErrBuildingMaxLevel = 5003,
    [pbr::OriginalName("ERR_BUILDING_UPGRADING")] ErrBuildingUpgrading = 5004,
    [pbr::OriginalName("ERR_BUILDING_POSITION_OCCUPIED")] ErrBuildingPositionOccupied = 5005,
    [pbr::OriginalName("ERR_BUILDING_CONFIG_NOT_FOUND")] ErrBuildingConfigNotFound = 5006,
    [pbr::OriginalName("ERR_BUILDING_LEVEL_CONFIG_NOT_FOUND")] ErrBuildingLevelConfigNotFound = 5007,
    [pbr::OriginalName("ERR_BUILDING_CONDITION_NOT_MET")] ErrBuildingConditionNotMet = 5008,
    [pbr::OriginalName("ERR_BUILDING_LEVEL_NOT_FOUND")] ErrBuildingLevelNotFound = 5009,
    /// <summary>
    /// 军队错误 (5100-5199)
    /// </summary>
    [pbr::OriginalName("ERR_ARMY_NOT_FOUND")] ErrArmyNotFound = 5100,
    [pbr::OriginalName("ERR_ARMY_FULL")] ErrArmyFull = 5101,
    [pbr::OriginalName("ERR_ARMY_LIMIT_REACHED")] ErrArmyLimitReached = 5102,
    /// <summary>
    /// 法术错误 (5200-5299)
    /// </summary>
    [pbr::OriginalName("ERR_SPELL_NOT_FOUND")] ErrSpellNotFound = 5200,
    [pbr::OriginalName("ERR_SPELL_ALREADY_DEPLOYED")] ErrSpellAlreadyDeployed = 5201,
    [pbr::OriginalName("ERR_SPELL_NOT_DEPLOYED")] ErrSpellNotDeployed = 5202,
    [pbr::OriginalName("ERR_SPELL_MAX_LEVEL")] ErrSpellMaxLevel = 5203,
    [pbr::OriginalName("ERR_SPELL_ALREADY_UNLOCKED")] ErrSpellAlreadyUnlocked = 5204,
    /// <summary>
    /// 背包错误 (6000-6999)
    /// </summary>
    [pbr::OriginalName("ERR_INVENTORY_FULL")] ErrInventoryFull = 6000,
    [pbr::OriginalName("ERR_INVENTORY_ITEM_NOT_FOUND")] ErrInventoryItemNotFound = 6001,
    [pbr::OriginalName("ERR_INVENTORY_INSUFFICIENT_QUANTITY")] ErrInventoryInsufficientQuantity = 6002,
    [pbr::OriginalName("ERR_INVENTORY_USE_LIMIT")] ErrInventoryUseLimit = 6003,
    /// <summary>
    /// 匹配错误 (7000-7999)
    /// </summary>
    [pbr::OriginalName("ERR_MATCH_ALREADY_IN_QUEUE")] ErrMatchAlreadyInQueue = 7000,
    [pbr::OriginalName("ERR_MATCH_NOT_IN_QUEUE")] ErrMatchNotInQueue = 7001,
    [pbr::OriginalName("ERR_MATCH_TIMEOUT")] ErrMatchTimeout = 7002,
    [pbr::OriginalName("ERR_MATCH_CANCELLED")] ErrMatchCancelled = 7003,
    /// <summary>
    /// 战斗错误 (8000-8999)
    /// </summary>
    [pbr::OriginalName("ERR_BATTLE_NOT_FOUND")] ErrBattleNotFound = 8000,
    [pbr::OriginalName("ERR_BATTLE_ALREADY_STARTED")] ErrBattleAlreadyStarted = 8001,
    [pbr::OriginalName("ERR_BATTLE_NOT_STARTED")] ErrBattleNotStarted = 8002,
    [pbr::OriginalName("ERR_BATTLE_ENDED")] ErrBattleEnded = 8003,
    [pbr::OriginalName("ERR_BATTLE_INVALID_ACTION")] ErrBattleInvalidAction = 8004,
    /// <summary>
    /// 系统错误 (9000-9999)
    /// </summary>
    [pbr::OriginalName("ERR_SYSTEM_MAINTENANCE")] ErrSystemMaintenance = 9000,
    [pbr::OriginalName("ERR_SYSTEM_OVERLOAD")] ErrSystemOverload = 9001,
    [pbr::OriginalName("ERR_CONFIG_NOT_FOUND")] ErrConfigNotFound = 9002,
    [pbr::OriginalName("ERR_CONFIG_INVALID_VERSION")] ErrConfigInvalidVersion = 9003,
    [pbr::OriginalName("ERR_SYSTEM_INTERNAL")] ErrSystemInternal = 9999,
    /// <summary>
    /// bigmap march (10000-11000)
    /// </summary>
    [pbr::OriginalName("ERR_BIGMAPMARCH_ALLOCATE_MARCHID_FAIL")] ErrBigmapmarchAllocateMarchidFail = 10000,
  }

  #endregion

}

#endregion Designer generated code
